### ISSUE TITLE
Undefined var or method thredded_current_user

### ISSUE THREAD

**Issue by hisea** [thredded/thredded#231]
I'm just getting started with thredded. My client likes it a lot.

Not sure if I my setup is correct,  got an error evaluating [top_nav.html.erb](https://github.com/thredded/thredded/blob/master/app/views/thredded/shared/_top_nav.html.erb#L9). 

I can confirm that adding the method to helper_method in application controller fixed it.

https://github.com/hisea/thredded/blob/master/app/controllers/thredded/application_controller.rb#L16

```
NameError - undefined local variable or method `thredded_current_user' for #<#<Class:0x007fbcd59389d0>:0x007fbcd5bf8530>:
   () Users/Hai/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/thredded-ba64fa21895b/app/views/thredded/shared/_top_nav.html.erb:9:in `___sers__ai__rbenv_versions_______lib_ruby_gems_______bundler_gems_thredded_ba__fa_____b_app_views_thredded_shared__top_nav_html_erb___293700746325224047_70224541061740'
```

**Comment by jayroh** [comment]
Hey @hisea! If at all possible, could you add a more comprehensive stack trace so we can see where this ends up error'ing out?

And I'm glad your client likes it! We'll do what we can to help out :)

**Comment by glebm** [comment]
Looks like `thredded_current_user` was not defined as a `helper_method`. However, we only use it in that one view (top_nav), and only if a standalone layout is being used (using default layout instead of an application layout). And our dummy app does not use a standalone layout, so we've never seen it.
Addressed by #234

**Comment by glebm** [comment]
Github auto-closed this :|
@hisea Should be fixed with the latest master, does it work now?

**Comment by hisea** [comment]
Getting a different error on this [line](https://github.com/thredded/thredded/blob/master/app/controllers/thredded/application_controller.rb#L41) now when not logged in:

```ruby
TypeError - nil is not a symbol nor a string:
   () Users/hai/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/thredded-7cf579b559ed/app/controllers/thredded/application_controller.rb:41:in `thredded_current_user'
   () Users/hai/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/thredded-7cf579b559ed/app/controllers/thredded/application_controller.rb:45:in `signed_in?'
  actionpack (4.2.6) lib/abstract_controller/helpers.rb:67:in `signed_in?'
   () Users/hai/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/thredded-7cf579b559ed/app/views/thredded/shared/_top_nav.html.erb:6:in `___sers_hai__rbenv_versions_______lib_ruby_gems_______bundler_gems_thredded__cf___b___ed_app_views_thredded_shared__top_nav_html_erb__739005407007249137_70121742331480'
  actionview (4.2.6) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.6) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.6) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.6) lib/action_view/template.rb:143:in `render'
  actionview (4.2.6) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  actionview (4.2.6) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.6) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.6) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.6) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.6) lib/action_view/renderer/renderer.rb:51:in `render_partial'
  actionview (4.2.6) lib/action_view/helpers/rendering_helper.rb:35:in `render'
```

**Comment by hisea** [comment]
working fine now with latest master after added following line to my initializer.

Thanks for the quick turnaround.

```ruby
Thredded.current_user_method = :"current_#{Thredded.user_class.name.underscore}"
```
