### ISSUE TITLE
session_path and new_session_path undefined

### ISSUE THREAD

**Issue by hisea** [thredded/thredded#242]
Not sure if this is the right place to ask questions.

I setup my main app with devise and a user model, but when accessing any page that includes the top nav partial, I get this error:

```
actionpack (4.2.6) lib/action_dispatch/routing/routes_proxy.rb:37:in `method_missing'
/usr/local/bundle/bundler/gems/thredded-7cf579b559ed/app/views/thredded/shared/_top_nav.html.erb:16:in `__usr_local_bundle_bundler_gems_thredded__cf___b___ed_app_views_thredded_shared__top_nav_html_erb___1697234560578219915_70351177746020'
actionview (4.2.6) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.6) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.6) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.6) lib/action_view/template.rb:143:in `render'
actionview (4.2.6) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
actionview (4.2.6) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
actionview (4.2.6) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
actionview (4.2.6) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
actionview (4.2.6) lib/action_view/renderer/partial_renderer.rb:309:in `render'
actionview (4.2.6) lib/action_view/renderer/renderer.rb:51:in `render_partial'
actionview (4.2.6) lib/action_view/helpers/rendering_helper.rb:35:in `render'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
/usr/local/bundle/bundler/gems/thredded-7cf579b559ed/app/views/thredded/shared/_header.html.erb:2:in `__usr_local_bundle_bundler_gems_thredded__cf___b___ed_app_views_thredded_shared__header_html_erb___1860852494254495711_70351177760120'
``` 

Just wondering what is the best practice to configure session_path and new_session_path?

Thanks

**Comment by glebm** [comment]
Unfortunately, these are not configurable yet, short of overriding [top_nav](https://github.com/thredded/thredded/blob/master/app/views/thredded/shared/_top_nav.html.erb).

**Comment by glebm** [comment]
Please try the latest master. I've added a partial that you can override for log in / log out links, and also change it to use devise routes by default: https://github.com/thredded/thredded/blob/16aaf81dd9fe5da042b7a691514c3ef77923e549/app/views/thredded/shared/_standalone_nav.html.erb

**Comment by hisea** [comment]
thanks
