### ISSUE TITLE
undefined method `sql_type' on Postgres

### ISSUE THREAD

**Issue by seanfcarroll** [thredded/thredded#302]
Steps to reproduce:

- Created a Rails 4.2.6 app with Devise
- Created a user model called Participant
- Added the Threaded gem and ran generator

Whenever I do an action that creates something in the DB, it fails on a call to https://github.com/thredded/db_text_search

Issue is here: https://github.com/thredded/db_text_search/blob/master/lib/db_text_search/case_insensitive.rb#L95

Postgres 9.5.1.

Do I need to install a Postgres extension perhaps?

```
 SQL (0.2ms)  UPDATE "thredded_messageboards" SET "posts_count" = COALESCE("posts_count", 0) + 1 WHERE "thredded_messageboards"."id" = $1  [["id", 1]]
  SQL (0.2ms)  UPDATE "thredded_topics" SET "posts_count" = COALESCE("posts_count", 0) + 1 WHERE "thredded_topics"."id" = $1  [["id", 1]]
  Thredded::UserDetail Load (0.4ms)  SELECT  "thredded_user_details".* FROM "thredded_user_details" WHERE "thredded_user_details"."user_id" = $1 LIMIT 1  [["user_id", 1]]
  SQL (0.2ms)  UPDATE "thredded_user_details" SET "posts_count" = COALESCE("posts_count", 0) + 1 WHERE "thredded_user_details"."id" = $1  [["id", 1]]
   (6.0ms)  COMMIT
[ActiveJob] [Thredded::AtNotifierJob] [34c276af-e2f7-4317-854c-f8fe5d99adb9] Performing Thredded::AtNotifierJob from Inline(default) with arguments: "Thredded::Post", 2
[ActiveJob] [Thredded::AtNotifierJob] [34c276af-e2f7-4317-854c-f8fe5d99adb9]   Thredded::Post Load (0.2ms)  SELECT  "thredded_posts".* FROM "thredded_posts" WHERE "thredded_posts"."id" = $1 LIMIT 1  [["id", 2]]
[ActiveJob] [Thredded::AtNotifierJob] [34c276af-e2f7-4317-854c-f8fe5d99adb9]   Thredded::Messageboard Load (0.2ms)  SELECT  "thredded_messageboards".* FROM "thredded_messageboards" WHERE "thredded_messageboards"."closed" = $1 AND "thredded_messageboards"."id" = $2  ORDER BY "thredded_messageboards"."topics_count" DESC LIMIT 1  [["closed", "f"], ["id", 1]]
[ActiveJob] [Thredded::AtNotifierJob] [34c276af-e2f7-4317-854c-f8fe5d99adb9] Performed Thredded::AtNotifierJob from Inline(default) in 3.57ms
Completed 500 Internal Server Error in 50ms (ActiveRecord: 20.6ms)

NoMethodError (undefined method `sql_type' for nil:NilClass):
  db_text_search (0.2.0) lib/db_text_search/case_insensitive.rb:95:in `block in column_case_sensitive?'
  db_text_search (0.2.0) lib/db_text_search.rb:28:in `match_adapter'
  db_text_search (0.2.0) lib/db_text_search/case_insensitive.rb:92:in `column_case_sensitive?'
  db_text_search (0.2.0) lib/db_text_search/case_insensitive.rb:73:in `block in adapter_class'
  db_text_search (0.2.0) lib/db_text_search.rb:28:in `match_adapter'
  db_text_search (0.2.0) lib/db_text_search/case_insensitive.rb:75:in `adapter_class'
  db_text_search (0.2.0) lib/db_text_search/case_insensitive.rb:13:in `initialize'
  thredded (0.3.2) app/models/thredded/post.rb:30:in `new'
  thredded (0.3.2) app/models/thredded/post.rb:30:in `readers_from_user_names'
  thredded (0.3.2) app/commands/thredded/notify_mentioned_users.rb:21:in `at_notifiable_members'
  thredded (0.3.2) app/commands/thredded/notify_mentioned_users.rb:9:in `run'
```

**Comment by seanfcarroll** [comment]
Solved.

I needed to add a name column

```
rails g migration add_name_to_participants name:string
```

The name column is referenced in the initializer.

https://github.com/thredded/thredded/blob/master/lib/generators/thredded/install/templates/initializer.rb#L12
