### ISSUE TITLE
Customizing admin breaks private topic for non-admins

### ISSUE THREAD

**Issue by wanqizhu** [thredded/thredded#342]
Hi,

I followed the Thredded installation guide and tried to customize the admin definition. Rather than using a binary field in my user_model, I have an integer auth_level that can take on various levels

So I added  

```
  def thredded_admin?
    return self.auth_level > 90
  end
```

to user.rb

Everything works fine for admins: I can view and send private message. However, if I login to an non-admin, the private topic page breaks:

```
Started GET "/forum/private-topics" for ::1 at 2016-07-18 10:14:37 -0500
Processing by Thredded::PrivateTopicsController#index as HTML
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 2]]
  Thredded::PrivateTopic Load (0.2ms)  SELECT  DISTINCT "thredded_private_topics".* FROM "thredded_private_topics" INNER JOIN "thredded_private_users" ON "thredded_private_users"."private_topic_id" = "thredded_private_topics"."id" WHERE "thredded_private_users"."user_id" = ?  ORDER BY "thredded_private_topics"."updated_at" DESC, "thredded_private_topics"."id" DESC LIMIT 50 OFFSET 0  [["user_id", 2]]
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" IN (1)
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" IN (1, 2)
  Thredded::UserPrivateTopicReadState Load (0.2ms)  SELECT "thredded_user_private_topic_read_states".* FROM "thredded_user_private_topic_read_states" WHERE "thredded_user_private_topic_read_states"."user_id" = ? AND "thredded_user_private_topic_read_states"."postable_id" IN (3, 2, 1)  [["user_id", 2]]
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 2
  Thredded::UserDetail Load (0.2ms)  SELECT  "thredded_user_details".* FROM "thredded_user_details" WHERE "thredded_user_details"."user_id" = ? LIMIT 1  [["user_id", 2]]
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/private_topics/_breadcrumbs.html.erb (0.4ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/private_topics/_form.html.erb (2.6ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/private_topics/index.html.erb within layouts/thredded/application (6.4ms)
Completed 500 Internal Server Error in 57ms

ActionView::Template::Error (First argument in form cannot contain nil or be empty):
    1: <%= form_for private_topic,
    2:              url:  private_topics_path(@private_topic),
    3:              html: { class: "thredded--form #{local_assigns[:css_class]}", 'data-thredded-topic-form' => true } do |form| %>
    4: 
  actionview (4.2.0) lib/action_view/helpers/form_helper.rb:432:in `form_for'
```

Any help would be greatly appreciated!

Wanqi

**Comment by jayroh** [comment]
And if you remove that `thredded_admin?` method from user everything starts
to work again?

**Comment by wanqizhu** [comment]
Actually, it seems like the issue was caused with me messing in the rails console. Not sure what I did, but I broke one user. Future signups now work correctly -- thanks!

**Comment by jayroh** [comment]
🎉

Thanks!

**Comment by pyrabbit** [comment]
@jayroh Not sure if it is worth resurrecting this topic again. I also experienced this issue yesterday when I ran the following commands in the Rails console.

```
user = User.find(2)
user.update_attributes(username: "frank")
```

Now the Frank user is generating Fatal Errors when attempting to access their private topics. I have the stack trace below. Does anything stick out to you that I can maybe help fix? This only happened with 1 out of the 3 users I did this with. They were, for the most part, brand new users.

```
I, [2017-04-24T15:21:41.123550 #15111]  INFO -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3] Started GET "/forum/private-topics" for 108.162.238.92 at 2017-04-24 15:21:41 +0000
I, [2017-04-24T15:21:41.124375 #15111]  INFO -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3] Processing by Thredded::PrivateTopicsController#index as HTML
D, [2017-04-24T15:21:41.128741 #15111] DEBUG -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3]   User Load (1.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2 ORDER BY `users`.`id` ASC LIMIT 1
D, [2017-04-24T15:21:41.131763 #15111] DEBUG -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3]   Thredded::PrivateTopic Load (1.4ms)  SELECT  DISTINCT `thredded_private_topics`.* FROM `thredded_private_topics` INNER JOIN `thredded_private_users` ON `thredded_private_users`.`private_topic_id` = `thredded_private_topics`.`id` WHERE `thredded_private_users`.`user_id` = 2 ORDER BY `thredded_private_topics`.`last_post_at` DESC, `thredded_private_topics`.`id` DESC LIMIT 30 OFFSET 0
D, [2017-04-24T15:21:41.133988 #15111] DEBUG -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3]   User Load (1.4ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1
D, [2017-04-24T15:21:41.136118 #15111] DEBUG -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3]   User Load (1.5ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 2
D, [2017-04-24T15:21:41.138315 #15111] DEBUG -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3]   Thredded::PrivateUser Load (1.4ms)  SELECT `thredded_private_users`.* FROM `thredded_private_users` WHERE `thredded_private_users`.`private_topic_id` = 1
D, [2017-04-24T15:21:41.140675 #15111] DEBUG -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3]   User Load (1.4ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` IN (1, 2)
D, [2017-04-24T15:21:41.142856 #15111] DEBUG -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3]   Thredded::UserPrivateTopicReadState Load (1.4ms)  SELECT `thredded_user_private_topic_read_states`.* FROM `thredded_user_private_topic_read_states` WHERE `thredded_user_private_topic_read_states`.`user_id` = 2 AND `thredded_user_private_topic_read_states`.`postable_id` = 1
D, [2017-04-24T15:21:41.143647 #15111] DEBUG -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3]   CACHE (0.0ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 2
D, [2017-04-24T15:21:41.147383 #15111] DEBUG -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3]   Thredded::UserDetail Load (1.5ms)  SELECT  `thredded_user_details`.* FROM `thredded_user_details` WHERE `thredded_user_details`.`user_id` = 2 LIMIT 1
I, [2017-04-24T15:21:41.147989 #15111]  INFO -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3]   Rendering /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/thredded-0.11.0/app/views/thredded/private_topics/index.html.erb within layouts/thredded
I, [2017-04-24T15:21:41.148592 #15111]  INFO -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3]   Rendered /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/thredded-0.11.0/app/views/thredded/private_topics/_breadcrumbs.html.erb (0.3ms)
I, [2017-04-24T15:21:41.149705 #15111]  INFO -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3]   Rendered /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/thredded-0.11.0/app/views/thredded/private_topics/_form.html.erb (0.9ms)
I, [2017-04-24T15:21:41.149779 #15111]  INFO -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3]   Rendered /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/thredded-0.11.0/app/views/thredded/private_topics/index.html.erb within layouts/thredded (1.7ms)
I, [2017-04-24T15:21:41.149961 #15111]  INFO -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3] Completed 500 Internal Server Error in 25ms (ActiveRecord: 11.4ms)
F, [2017-04-24T15:21:41.151821 #15111] FATAL -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3]   
F, [2017-04-24T15:21:41.151858 #15111] FATAL -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3] ActionView::Template::Error (First argument in form cannot contain nil or be empty):
F, [2017-04-24T15:21:41.151974 #15111] FATAL -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3]     1: <%= form_for private_topic,
[95e1f8d0-753d-472d-9599-acda1dc1ccc3]     2:              url: private_topics_path(@private_topic),
[95e1f8d0-753d-472d-9599-acda1dc1ccc3]     3:              html: {
[95e1f8d0-753d-472d-9599-acda1dc1ccc3]     4:                  class: "thredded--form thredded--new-private-topic-form #{local_assigns[:css_class]}",
F, [2017-04-24T15:21:41.151998 #15111] FATAL -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3]   
F, [2017-04-24T15:21:41.152084 #15111] FATAL -- : [95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/helpers/form_helper.rb:438:in `form_for'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] thredded (0.11.0) app/views/thredded/private_topics/_form.html.erb:1:in `__opt_rubies_ruby_______lib_ruby_gems_______gems_thredded________app_views_thredded_private_topics__form_html_erb___297206623417719793_47241570024880'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/template.rb:159:in `block in render'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/notifications.rb:166:in `instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/template.rb:354:in `instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/template.rb:157:in `render'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/renderer/partial_renderer.rb:343:in `render_partial'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/renderer/partial_renderer.rb:311:in `block in render'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/notifications.rb:164:in `block in instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/notifications.rb:164:in `instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/renderer/partial_renderer.rb:310:in `render'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/renderer/renderer.rb:47:in `render_partial'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/helpers/rendering_helper.rb:35:in `render'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] thredded (0.11.0) app/views/thredded/private_topics/index.html.erb:13:in `block (2 levels) in __opt_rubies_ruby_______lib_ruby_gems_______gems_thredded________app_views_thredded_private_topics_index_html_erb___2587043591227426356_47241570191360'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/helpers/capture_helper.rb:39:in `capture'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/helpers/tag_helper.rb:107:in `content_tag'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] thredded (0.11.0) app/views/thredded/private_topics/index.html.erb:6:in `block in __opt_rubies_ruby_______lib_ruby_gems_______gems_thredded________app_views_thredded_private_topics_index_html_erb___2587043591227426356_47241570191360'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/helpers/capture_helper.rb:39:in `capture'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/helpers/capture_helper.rb:153:in `content_for'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] thredded (0.11.0) app/helpers/thredded/application_helper.rb:30:in `thredded_page'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] thredded (0.11.0) app/views/thredded/private_topics/index.html.erb:5:in `__opt_rubies_ruby_______lib_ruby_gems_______gems_thredded________app_views_thredded_private_topics_index_html_erb___2587043591227426356_47241570191360'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/template.rb:159:in `block in render'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/notifications.rb:166:in `instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/template.rb:354:in `instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/template.rb:157:in `render'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/notifications.rb:164:in `block in instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/notifications.rb:164:in `instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/renderer/template_renderer.rb:14:in `render'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/renderer/renderer.rb:42:in `render_template'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/renderer/renderer.rb:23:in `render'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/rendering.rb:104:in `_render_template'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/rendering.rb:83:in `render_to_body'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/abstract_controller/rendering.rb:26:in `render'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/rendering.rb:36:in `render'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activerecord (5.0.2) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] wicked_pdf (1.1.0) lib/wicked_pdf/pdf_helper.rb:42:in `render_with_wicked_pdf'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] wicked_pdf (1.1.0) lib/wicked_pdf/pdf_helper.rb:27:in `render'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/implicit_render.rb:36:in `default_render'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/abstract_controller/base.rb:188:in `process_action'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/callbacks.rb:126:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/callbacks.rb:455:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/notifications.rb:164:in `block in instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/notifications.rb:164:in `instrument'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activerecord (5.0.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/abstract_controller/base.rb:126:in `process'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionview (5.0.2) lib/action_view/rendering.rb:30:in `process'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal.rb:190:in `dispatch'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_controller/metal.rb:262:in `dispatch'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `each'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `serve'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:725:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] railties (5.0.2) lib/rails/engine.rb:522:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] railties (5.0.2) lib/rails/railtie.rb:193:in `public_send'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] railties (5.0.2) lib/rails/railtie.rb:193:in `method_missing'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/routing/mapper.rb:46:in `serve'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `each'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `serve'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:725:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] warden (1.2.6) lib/warden/manager.rb:34:in `catch'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] warden (1.2.6) lib/warden/manager.rb:34:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] rack (2.0.1) lib/rack/etag.rb:25:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] rack (2.0.1) lib/rack/head.rb:12:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] railties (5.0.2) lib/rails/rack/logger.rb:36:in `call_app'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] railties (5.0.2) lib/rails/rack/logger.rb:24:in `block in call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/tagged_logging.rb:26:in `tagged'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `tagged'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] railties (5.0.2) lib/rails/rack/logger.rb:24:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] rack (2.0.1) lib/rack/method_override.rb:22:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] rack (2.0.1) lib/rack/runtime.rb:22:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] activesupport (5.0.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] actionpack (5.0.2) lib/action_dispatch/middleware/static.rb:136:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] railties (5.0.2) lib/rails/engine.rb:522:in `call'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] passenger (4.0.60) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] passenger (4.0.60) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] passenger (4.0.60) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
[95e1f8d0-753d-472d-9599-acda1dc1ccc3] passenger (4.0.60) lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
```

**Comment by glebm** [comment]
@pyrabbit Thanks, that's very helpful (though not related to this original issue).

Looks like that user is blocked (see Moderation). We had a bug where the private messages page was broken for blocked users (fixed with the commit above).
