### ISSUE TITLE
The page you were looking for doesn't exist.

### ISSUE THREAD

**Issue by frankie-loves-jesus** [thredded/thredded#434]
Not sure what I did wrong:
- Installed Devise and created a User model
- Followed the steps in https://github.com/thredded/thredded/blob/master/README.md
- Migrated the database and precompiled the assets
- Ran Puma

Now at my site I see:

```
The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

If you are the application owner check the logs for more information.
```

I'm on Rails 5.0.0.1. My `log/production.log` says:

```
I, [2016-10-24T13:09:11.902306 #90396]  INFO -- : [1b2dd6bf-94c5-4884-a1b1-78126b7a3378] Started GET "/" at 2016-10-24 13:09:11 +0200
F, [2016-10-24T13:09:11.905118 #90396] FATAL -- : [1b2dd6bf-94c5-4884-a1b1-78126b7a3378]
F, [2016-10-24T13:09:11.905227 #90396] FATAL -- : [1b2dd6bf-94c5-4884-a1b1-78126b7a3378] ActionController::RoutingError (No route matches [GET] "/"):
F, [2016-10-24T13:09:11.905274 #90396] FATAL -- : [1b2dd6bf-94c5-4884-a1b1-78126b7a3378]
F, [2016-10-24T13:09:11.905318 #90396] FATAL -- : [1b2dd6bf-94c5-4884-a1b1-78126b7a3378] actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
F, [2016-10-24T13:09:11.905355 #90396] FATAL -- : [1b2dd6bf-94c5-4884-a1b1-78126b7a3378] actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
F, [2016-10-24T13:09:11.905402 #90396] FATAL -- : [1b2dd6bf-94c5-4884-a1b1-78126b7a3378] railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
F, [2016-10-24T13:09:11.905450 #90396] FATAL -- : [1b2dd6bf-94c5-4884-a1b1-78126b7a3378] railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
F, [2016-10-24T13:09:11.905483 #90396] FATAL -- : [1b2dd6bf-94c5-4884-a1b1-78126b7a3378] activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
[...]
```

And `routes.rb`:

```
Rails.application.routes.draw do
  mount Thredded::Engine => '/forum'
end
```

**Comment by timdiggins** [comment]
@frankie-loves-jesus -- you don't have anything defined for your "root" path in routes, so this error would be expected if you are going to the root (/). Try going to /forum

**Comment by frankie-loves-jesus** [comment]
Hello!

Unfortunately going to /forum creates:
```
# cat log/production.log
I, [2016-10-24T15:00:21.194365 #8923]  INFO -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] Started GET "/forum" at 2016-10-24 15:00:21 +0200
I, [2016-10-24T15:00:21.214428 #8923]  INFO -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] Processing by Thredded::MessageboardsController#index as HTML
I, [2016-10-24T15:00:21.272432 #8923]  INFO -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] Completed 500 Internal Server Error in 57ms (ActiveRecord: 5.3ms)
F, [2016-10-24T15:00:21.274882 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f]
F, [2016-10-24T15:00:21.278873 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] NoMethodError (undefined method `current_user' for #<Thredded::MessageboardsController:0x000852cb8041b8>):
F, [2016-10-24T15:00:21.278970 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f]
F, [2016-10-24T15:00:21.279031 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] thredded (0.7.0) app/controllers/thredded/application_controller.rb:44:in `thredded_current_user'
F, [2016-10-24T15:00:21.279081 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] thredded (0.7.0) app/controllers/thredded/application_controller.rb:88:in `pundit_user'
F, [2016-10-24T15:00:21.279188 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] pundit (1.1.0) lib/pundit.rb:284:in `pundit_policy_scope'
F, [2016-10-24T15:00:21.279226 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] pundit (1.1.0) lib/pundit.rb:226:in `policy_scope'
F, [2016-10-24T15:00:21.279274 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] thredded (0.7.0) app/controllers/thredded/messageboards_controller.rb:10:in `index'
F, [2016-10-24T15:00:21.279309 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
F, [2016-10-24T15:00:21.279341 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/abstract_controller/base.rb:188:in `process_action'
F, [2016-10-24T15:00:21.279373 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
F, [2016-10-24T15:00:21.279417 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
F, [2016-10-24T15:00:21.279451 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activesupport (5.0.0.1) lib/active_support/callbacks.rb:126:in `call'
F, [2016-10-24T15:00:21.279484 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activesupport (5.0.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
F, [2016-10-24T15:00:21.279554 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
F, [2016-10-24T15:00:21.279591 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
F, [2016-10-24T15:00:21.279624 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
F, [2016-10-24T15:00:21.279667 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
F, [2016-10-24T15:00:21.279734 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
F, [2016-10-24T15:00:21.279772 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
F, [2016-10-24T15:00:21.279831 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
F, [2016-10-24T15:00:21.279864 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
F, [2016-10-24T15:00:21.279909 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
F, [2016-10-24T15:00:21.279946 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `instrument'
F, [2016-10-24T15:00:21.280038 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
F, [2016-10-24T15:00:21.280081 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
F, [2016-10-24T15:00:21.280125 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
F, [2016-10-24T15:00:21.280160 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/abstract_controller/base.rb:126:in `process'
F, [2016-10-24T15:00:21.280208 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionview (5.0.0.1) lib/action_view/rendering.rb:30:in `process'
F, [2016-10-24T15:00:21.280241 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_controller/metal.rb:190:in `dispatch'
F, [2016-10-24T15:00:21.280273 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_controller/metal.rb:262:in `dispatch'
F, [2016-10-24T15:00:21.280304 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
F, [2016-10-24T15:00:21.280336 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
F, [2016-10-24T15:00:21.280406 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
F, [2016-10-24T15:00:21.280497 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
F, [2016-10-24T15:00:21.280536 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
F, [2016-10-24T15:00:21.280569 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
F, [2016-10-24T15:00:21.280601 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
F, [2016-10-24T15:00:21.280640 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] railties (5.0.0.1) lib/rails/railtie.rb:193:in `public_send'
F, [2016-10-24T15:00:21.280675 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] railties (5.0.0.1) lib/rails/railtie.rb:193:in `method_missing'
F, [2016-10-24T15:00:21.280708 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
F, [2016-10-24T15:00:21.280739 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/routing/mapper.rb:46:in `serve'
F, [2016-10-24T15:00:21.280770 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
F, [2016-10-24T15:00:21.280801 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
F, [2016-10-24T15:00:21.280832 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
F, [2016-10-24T15:00:21.280950 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
F, [2016-10-24T15:00:21.281040 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
F, [2016-10-24T15:00:21.281100 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] warden (1.2.6) lib/warden/manager.rb:34:in `catch'
F, [2016-10-24T15:00:21.281148 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] warden (1.2.6) lib/warden/manager.rb:34:in `call'
F, [2016-10-24T15:00:21.281231 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] rack (2.0.1) lib/rack/etag.rb:25:in `call'
F, [2016-10-24T15:00:21.281298 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
F, [2016-10-24T15:00:21.281369 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] rack (2.0.1) lib/rack/head.rb:12:in `call'
F, [2016-10-24T15:00:21.281431 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
F, [2016-10-24T15:00:21.281490 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
F, [2016-10-24T15:00:21.281524 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
F, [2016-10-24T15:00:21.281555 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
F, [2016-10-24T15:00:21.281586 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
F, [2016-10-24T15:00:21.281774 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
F, [2016-10-24T15:00:21.281815 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
F, [2016-10-24T15:00:21.281853 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
F, [2016-10-24T15:00:21.281884 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
F, [2016-10-24T15:00:21.281918 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
F, [2016-10-24T15:00:21.281949 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
F, [2016-10-24T15:00:21.281980 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
F, [2016-10-24T15:00:21.282011 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
F, [2016-10-24T15:00:21.282054 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
F, [2016-10-24T15:00:21.282141 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
F, [2016-10-24T15:00:21.282180 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
F, [2016-10-24T15:00:21.282213 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
F, [2016-10-24T15:00:21.282243 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
F, [2016-10-24T15:00:21.282274 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] rack (2.0.1) lib/rack/method_override.rb:22:in `call'
F, [2016-10-24T15:00:21.282326 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] rack (2.0.1) lib/rack/runtime.rb:22:in `call'
F, [2016-10-24T15:00:21.282382 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
F, [2016-10-24T15:00:21.282415 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
F, [2016-10-24T15:00:21.282449 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
F, [2016-10-24T15:00:21.282480 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
F, [2016-10-24T15:00:21.282548 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] puma (3.6.0) lib/puma/configuration.rb:225:in `call'
F, [2016-10-24T15:00:21.282582 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
F, [2016-10-24T15:00:21.282613 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] puma (3.6.0) lib/puma/server.rb:415:in `process_client'
F, [2016-10-24T15:00:21.282720 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] puma (3.6.0) lib/puma/server.rb:275:in `block in run'
F, [2016-10-24T15:00:21.282757 #8923] FATAL -- : [75c9d6e2-5926-4714-9266-7c18e72c996f] puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by timdiggins** [comment]
Are you running it in production mode deliberately? (I.e. Does it work fine in development mode?). 

If not, might be good to get a basic login page and/or some other content working first before integrating thredded.

**Comment by jayroh** [comment]
Agree with Tim - at first it does seem like a routing issue. What does
`rake routes` output look like?

**Comment by jayroh** [comment]
You may not have configured Thredded to point at your application's
"current_user" method.

`    def thredded_current_user

      send(Thredded.current_user_method) || NullUser.new
    end`


Make sure that is configured with the method you have in your main
application. For most it's "current_user", so that's what it is
defaulting to. If you don't have that defined, or the gem you're using
doesn't define it, then that's what is happening.
