### ISSUE TITLE
NameError: uninitialized constant Thredded::VERSION

### ISSUE THREAD

**Issue by mfisher31** [thredded/thredded#480]
Receiving this message when running in production environment.  This happens when creating a new topic and in rails console as well.

Gem release version: 0.8.2

```
Loading production environment (Rails 5.0.0.1)
irb(main):001:0> Thredded
=> Thredded
irb(main):002:0> Thredded::VERSION
NameError: uninitialized constant Thredded::VERSION
	from (irb):2
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
irb(main):003:0>
```

**Comment by mfisher31** [comment]
note that I don't not have this problem when ```RAILS_ENV=development```

**Comment by mfisher31** [comment]
and output from unicorn/rails log:

```
D, [2016-11-19T19:56:25.390095 #19] DEBUG -- : [9235a116-fbc9-4bae-8ada-fb1d5e753fa3]    (0.9ms)  ROLLBACK
I, [2016-11-19T19:56:25.391127 #19]  INFO -- : [9235a116-fbc9-4bae-8ada-fb1d5e753fa3] Completed 500 Internal Server Error in 235ms (ActiveRecord: 12.7ms)
F, [2016-11-19T19:56:25.392331 #19] FATAL -- : [9235a116-fbc9-4bae-8ada-fb1d5e753fa3]
F, [2016-11-19T19:56:25.392471 #19] FATAL -- : [9235a116-fbc9-4bae-8ada-fb1d5e753fa3] NameError (uninitialized constant Thredded::VERSION):
F, [2016-11-19T19:56:25.392609 #19] FATAL -- : [9235a116-fbc9-4bae-8ada-fb1d5e753fa3]
F, [2016-11-19T19:56:25.392732 #19] FATAL -- : [9235a116-fbc9-4bae-8ada-fb1d5e753fa3] thredded (0.8.3commands) thredded/create_messageboard.rb:39:in `first_post_content'
F, [2016-11-19T19:56:25.392887 #19] FATAL -- : [9235a116-fbc9-4bae-8ada-fb1d5e753fa3] thredded (0.8.3commands) thredded/create_messageboard.rb:25:in `block in run'
F, [2016-11-19T19:56:25.392998 #19] FATAL -- : [9235a116-fbc9-4bae-8ada-fb1d5e753fa3] activerecord (5.0.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
```

**Comment by glebm** [comment]
Fixed in https://github.com/thredded/thredded/commit/672f63a89d1ed77a90c72c78c744d54bba33d196
Please update to Thredded v0.8.4!

**Comment by mfisher31** [comment]
yep, doing that right now. thanks!
