### ISSUE TITLE
Randomly occurring failure

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#531]
There's a randomly occurring failure when smileys are added, when js tests will try to pull in the emoji which doesn't exist.

```
  1) View a topic with super-rich content (smoke test) can view a topic with very rich content (smoke test)
     Failure/Error: raise ActionController::RoutingError, "No route matches [#{env['REQUEST_METHOD']}] #{env['PATH_INFO'].inspect}"
     
     ActionController::RoutingError:
       No route matches [GET] "/emoji/unicode/1f604.png"
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:36:in `call_app'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `block in call'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `block in tagged'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `tagged'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `call'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/request_store-1.3.1/lib/request_store/middleware.rb:9:in `call'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/request_id.rb:24:in `call'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/activesupport-5.0.0.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/static.rb:136:in `call'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/railties-5.0.0.1/lib/rails/engine.rb:522:in `call'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/rack-2.0.1/lib/rack/urlmap.rb:68:in `block in call'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `each'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `call'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/capybara-2.9.0/lib/capybara/server.rb:43:in `call'
     # /Users/tim/.rvm/gems/ruby-2.3.1@thredded/gems/rack-2.0.1/lib/rack/handler/webrick.rb:86:in `service'
     # /Users/tim/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
     # /Users/tim/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
     # /Users/tim/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
     # ------------------
     # --- Caused by: ---
     # Capybara::CapybaraError:
     #   Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
     #   ./spec/support/thredded_reset.rb:5:in `block (2 levels) in <top (required)>'

Finished in 9.19 seconds (files took 4.5 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/features/thredded/user_views_a_topic_with_super_rich_content_spec.rb:9 # View a topic with super-rich content (smoke test) can view a topic with very rich content (smoke test)
```

Have made a work-in-progress PR to highlight and work out solution.

**Comment by glebm** [comment]
I've added the FakeContent emoji to the dummy app above.

**Comment by timdiggins** [comment]
@glebm I think that's a good call. I was torn between bloating the repo (yuck!) and adding unnecessary web stubbing (which would actually speed things up minorly, but just adds complexity we don't need).
