### ISSUE TITLE
Conflict with cloudfront?

### ISSUE THREAD

**Issue by BobWalsh** [thredded/thredded#579]
We have an existing app that I am adding Thredded to (rails 5, with turbolinks5, and cloudfront, using our application layout). certain functions, like opening a topic, trigger this weird (to me) bug:
<img width="1754" alt="nomethoderror_at__test_test-topic-friday_and_developer_tools_-_http___localhost_3200_beats" src="https://cloud.githubusercontent.com/assets/5097/25292918/344d11c6-268d-11e7-90b2-350bb30e2d58.png">

Any suggestions on a fix, or even how to better diagnose the issue? Here's the stack trace:

```
Started GET "/forum/test/test-topic-friday" for ::1 at 2017-04-21 09:12:35 -0700
Processing by Thredded::TopicsController#show as HTML
  Parameters: {"messageboard_id"=>"test", "id"=>"test-topic-friday"}
  Thredded::Messageboard Load (1.7ms)  SELECT  "thredded_messageboards".* FROM "thredded_messageboards" WHERE "thredded_messageboards"."closed" = $1 AND "thredded_messageboards"."slug" = $2 LIMIT $3  [["closed", false], ["slug", "test"], ["LIMIT", 1]]
  Thredded::Topic Load (0.6ms)  SELECT  "thredded_topics".* FROM "thredded_topics" WHERE "thredded_topics"."messageboard_id" = $1 AND "thredded_topics"."slug" = $2 ORDER BY "thredded_topics"."id" ASC LIMIT $3  [["messageboard_id", 2], ["slug", "test-topic-friday"], ["LIMIT", 1]]
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."auth_token" = $1 LIMIT $2  [["auth_token", "pkcDBfi2SXyiTWuaJR7Z4mzS"], ["LIMIT", 1]]
  Thredded::Messageboard Load (0.5ms)  SELECT "thredded_messageboards".* FROM "thredded_messageboards" WHERE "thredded_messageboards"."closed" = $1  [["closed", false]]
  Thredded::Post Load (0.6ms)  SELECT  "thredded_posts".* FROM "thredded_posts" WHERE "thredded_posts"."postable_id" = $1 AND (("thredded_posts"."moderation_state" != 2 OR "thredded_posts"."user_id" = 12) OR "thredded_posts"."messageboard_id" IN (1, 2)) ORDER BY "thredded_posts"."created_at" ASC, "thredded_posts"."id" ASC LIMIT $2 OFFSET $3  [["postable_id", 5], ["LIMIT", 50], ["OFFSET", 0]]
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 12
  Thredded::Messageboard Load (0.5ms)  SELECT "thredded_messageboards".* FROM "thredded_messageboards" WHERE "thredded_messageboards"."closed" = $1 AND "thredded_messageboards"."id" = 2  [["closed", false]]
  Thredded::UserTopicReadState Load (0.3ms)  SELECT  "thredded_user_topic_read_states".* FROM "thredded_user_topic_read_states" WHERE "thredded_user_topic_read_states"."user_id" = $1 AND "thredded_user_topic_read_states"."postable_id" = $2 LIMIT $3  [["user_id", 12], ["postable_id", 5], ["LIMIT", 1]]
  Thredded::UserTopicFollow Load (0.2ms)  SELECT  "thredded_user_topic_follows".* FROM "thredded_user_topic_follows" WHERE "thredded_user_topic_follows"."user_id" = $1 AND "thredded_user_topic_follows"."topic_id" = $2 LIMIT $3  [["user_id", 12], ["topic_id", 5], ["LIMIT", 1]]
  CACHE (0.0ms)  SELECT  "thredded_user_topic_read_states".* FROM "thredded_user_topic_read_states" WHERE "thredded_user_topic_read_states"."user_id" = $1 AND "thredded_user_topic_read_states"."postable_id" = $2 LIMIT $3  [["user_id", 12], ["postable_id", 5], ["LIMIT", 1]]
  Rendering layouts/application.html.slim
  Rendering /Users/bobwalsh/.rvm/gems/ruby-2.4.0/gems/thredded-0.7.0/app/views/thredded/topics/show.html.erb within layouts/application
  Rendered /Users/bobwalsh/.rvm/gems/ruby-2.4.0/gems/thredded-0.7.0/app/views/thredded/shared/_breadcrumbs.html.erb (0.7ms)
  Thredded::Topic Load (0.5ms)  SELECT  "thredded_topics".* FROM "thredded_topics" WHERE "thredded_topics"."id" = $1 LIMIT $2  [["id", 5], ["LIMIT", 1]]
  Thredded::Category Load (0.4ms)  SELECT "thredded_categories".* FROM "thredded_categories" INNER JOIN "thredded_topic_categories" ON "thredded_categories"."id" = "thredded_topic_categories"."category_id" WHERE "thredded_topic_categories"."topic_id" = $1  [["topic_id", 5]]
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 12], ["LIMIT", 1]]
  Rendered /Users/bobwalsh/.rvm/gems/ruby-2.4.0/gems/thredded-0.7.0/app/views/thredded/users/_link.html.erb (0.7ms)
  Rendered /Users/bobwalsh/.rvm/gems/ruby-2.4.0/gems/thredded-0.7.0/app/views/thredded/topics/_followers.html.erb (0.7ms)
  Rendered /Users/bobwalsh/.rvm/gems/ruby-2.4.0/gems/thredded-0.7.0/app/views/thredded/topics/_header.html.erb (18.3ms)
  Rendered /Users/bobwalsh/.rvm/gems/ruby-2.4.0/gems/thredded-0.7.0/app/views/thredded/topics/show.html.erb within layouts/application (43.0ms)
  Rendered layouts/application.html.slim (44.5ms)
Completed 500 Internal Server Error in 76ms (ActiveRecord: 6.9ms)


/Users/bobwalsh/.rvm/gems/ruby-2.4.0/gems/appsignal-2.1.2/lib/appsignal/utils/params_sanitizer.rb:19: warning: constant ::Fixnum is deprecated
DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead. (called from initialize at /Users/bobwalsh/.rvm/gems/ruby-2.4.0/gems/better_errors-2.1.1/lib/better_errors/raised_exception.rb:7)
DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead. (called from initialize at /Users/bobwalsh/.rvm/gems/ruby-2.4.0/gems/better_errors-2.1.1/lib/better_errors/raised_exception.rb:8)

NoMethodError - undefined method `to_a' for #<Thredded::TopicPostsPageView:0x007fd572502e50>
Did you mean?  to_s:
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/renderer/partial_renderer.rb:406:in `collection_from_options'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/renderer/partial_renderer.rb:373:in `setup'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/renderer/partial_renderer.rb:296:in `render'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/renderer/renderer.rb:47:in `render_partial'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/renderer/renderer.rb:21:in `render'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/helpers/rendering_helper.rb:32:in `render'
  thredded (0.7.0) app/views/thredded/topics/show.html.erb:11:in `block (2 levels) in ___sers_bobwalsh__rvm_gems_ruby_______gems_thredded_______app_views_thredded_topics_show_html_erb___106641292417512855_70277357981500'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/helpers/capture_helper.rb:39:in `capture'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/helpers/tag_helper.rb:107:in `content_tag'
  thredded (0.7.0) app/views/thredded/topics/show.html.erb:7:in `block in ___sers_bobwalsh__rvm_gems_ruby_______gems_thredded_______app_views_thredded_topics_show_html_erb___106641292417512855_70277357981500'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/helpers/capture_helper.rb:39:in `capture'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/helpers/capture_helper.rb:153:in `content_for'
  thredded (0.7.0) app/helpers/thredded/application_helper.rb:23:in `thredded_page'
  thredded (0.7.0) app/views/thredded/topics/show.html.erb:6:in `___sers_bobwalsh__rvm_gems_ruby_______gems_thredded_______app_views_thredded_topics_show_html_erb___106641292417512855_70277357981500'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/template.rb:159:in `block in render'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/notifications.rb:166:in `instrument'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/template.rb:354:in `instrument'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/template.rb:157:in `render'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/notifications.rb:164:in `block in instrument'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  appsignal (2.1.2) lib/appsignal/hooks/active_support_notifications.rb:25:in `instrument'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/notifications.rb:164:in `instrument'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  skylight (1.1.0) lib/skylight/probes/action_view.rb:32:in `block in render_with_layout'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/notifications.rb:164:in `block in instrument'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  appsignal (2.1.2) lib/appsignal/hooks/active_support_notifications.rb:25:in `instrument'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/notifications.rb:164:in `instrument'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
  skylight (1.1.0) lib/skylight/probes/action_view.rb:31:in `render_with_layout'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/renderer/template_renderer.rb:14:in `render'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/renderer/renderer.rb:42:in `render_template'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/renderer/renderer.rb:23:in `render'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/rendering.rb:104:in `_render_template'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal/streaming.rb:217:in `_render_template'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/rendering.rb:83:in `render_to_body'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/abstract_controller/rendering.rb:26:in `render'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal/rendering.rb:36:in `render'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/bobwalsh/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/core_ext/benchmark.rb:12:in `ms'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activerecord/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal/instrumentation.rb:43:in `render'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal/implicit_render.rb:36:in `default_render'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/abstract_controller/base.rb:188:in `process_action'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal/rendering.rb:30:in `process_action'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/callbacks.rb:126:in `call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/callbacks.rb:455:in `call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/callbacks.rb:90:in `run_callbacks'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/abstract_controller/callbacks.rb:19:in `process_action'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal/rescue.rb:20:in `process_action'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/notifications.rb:164:in `block in instrument'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  appsignal (2.1.2) lib/appsignal/hooks/active_support_notifications.rb:25:in `instrument'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/notifications.rb:164:in `instrument'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activerecord/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/abstract_controller/base.rb:126:in `process'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionview/lib/action_view/rendering.rb:30:in `process'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal.rb:190:in `dispatch'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_controller/metal.rb:262:in `dispatch'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/routing/route_set.rb:32:in `serve'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/journey/router.rb:39:in `block in serve'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/journey/router.rb:26:in `serve'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/routing/route_set.rb:725:in `call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/railties/lib/rails/engine.rb:522:in `call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/railties/lib/rails/railtie.rb:193:in `method_missing'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/routing/mapper.rb:46:in `serve'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/journey/router.rb:39:in `block in serve'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/journey/router.rb:26:in `serve'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/routing/route_set.rb:725:in `call'
  omniauth (1.6.1) lib/omniauth/strategy.rb:189:in `call!'
  omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
  omniauth (1.6.1) lib/omniauth/builder.rb:63:in `call'
  app/services/cloudfront_constraint.rb:11:in `call'
  bullet (5.5.1) lib/bullet/rack.rb:10:in `call'
  jquery-fileupload-rails (0.4.7) lib/jquery/fileupload/rails/middleware.rb:14:in `_call'
  jquery-fileupload-rails (0.4.7) lib/jquery/fileupload/rails/middleware.rb:10:in `call'
  rack (2.0.1) lib/rack/etag.rb:25:in `call'
  rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
  rack (2.0.1) lib/rack/head.rb:12:in `call'
  rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
  rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/middleware/cookies.rb:613:in `call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activerecord/lib/active_record/migration.rb:553:in `call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/callbacks.rb:90:in `run_callbacks'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/middleware/executor.rb:12:in `call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  appsignal (2.1.2) lib/appsignal/rack/rails_instrumentation.rb:29:in `call_with_appsignal_monitoring'
  appsignal (2.1.2) lib/appsignal/rack/rails_instrumentation.rb:14:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/railties/lib/rails/rack/logger.rb:36:in `call_app'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/railties/lib/rails/rack/logger.rb:24:in `block in call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/tagged_logging.rb:69:in `block in tagged'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/tagged_logging.rb:26:in `tagged'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/activesupport/lib/active_support/tagged_logging.rb:69:in `tagged'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/railties/lib/rails/rack/logger.rb:24:in `call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/middleware/request_id.rb:24:in `call'
  rack (2.0.1) lib/rack/method_override.rb:22:in `call'
  rack (2.0.1) lib/rack/runtime.rb:22:in `call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/middleware/executor.rb:12:in `call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/actionpack/lib/action_dispatch/middleware/static.rb:136:in `call'
  rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
   () Users/bobwalsh/.rvm/gems/ruby-2.4.0/bundler/gems/rails-b5c30f336bc7/railties/lib/rails/engine.rb:522:in `call'
  rack (2.0.1) lib/rack/deflater.rb:35:in `call'
  rack (2.0.1) lib/rack/handler/webrick.rb:86:in `service'
  /Users/bobwalsh/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
  /Users/bobwalsh/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
  /Users/bobwalsh/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'

```

**Comment by glebm** [comment]
Upgrade Thredded to the latest version.
