### ISSUE TITLE
Could not log "render_collection.action_view" event. NoMethodError: undefined method `sub' for nil:NilClass 

### ISSUE THREAD

**Issue by igorkasyanchuk** [thredded/thredded#586]
```
  Rendered /usr/local/rvm/gems/ruby-2.3.3/gems/thredded-0.12.1/app/views/thredded/posts_common/_content.html.erb (3.0ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.3/gems/thredded-0.12.1/app/views/thredded/private_posts/_content.html.erb (4.9ms)

Could not log "render_collection.action_view" event. NoMethodError: undefined method `sub' for nil:NilClass ["/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/log_subscriber.rb:33:in `from_rails_root'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/log_subscriber.rb:17:in `block in render_template'",
"/usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/logger.rb:427:in `add'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/logger.rb:77:in `add'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/logger.rb:15:in `block (2 levels) in broadcast'",
"/usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/logger.rb:489:in `info'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/log_subscriber.rb:93:in `info'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/log_subscriber.rb:16:in `render_template'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/subscriber.rb:100:in `finish'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/log_subscriber.rb:83:in `finish'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/notifications/fanout.rb:102:in `finish'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/notifications/fanout.rb:46:in `block in finish'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/notifications/fanout.rb:46:in `each'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/notifications/fanout.rb:46:in `finish'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:36:in `finish'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:25:in `instrument'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/thredded-0.12.1/lib/thredded/collection_to_strings_with_cache_renderer.rb:15:in `render_collection_to_strings_with_cache'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/thredded-0.12.1/app/helpers/thredded/render_helper.rb:9:in `render_collection_to_strings_with_cache'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/thredded-0.12.1/app/helpers/thredded/application_helper.rb:76:in `render_posts'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/thredded-0.12.1/app/views/thredded/private_topics/show.html.erb:14:in `block (2 levels) in __usr_local_rvm_gems_ruby_______gems_thredded________app_views_thredded_private_topics_show_html_erb___3032644149913108886_161061600'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:38:in `capture'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/helpers/tag_helper.rb:106:in `content_tag'",
"/usr/local/rvm/gems/ruby-2.3.3/gems/thredded-0.12.1/app/views/thredded/private_topics/show.html.erb:7:in `block in __usr_local_rvm_gems_ruby_______gems_thredded________app_views_thredded_private_topics_show_html_erb___3032644149913108886_161061600'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:38:in `capture'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:152:in `content_for'", "/usr/local/rvm/gems/ruby-2.3.3/gems/thredded-0.12.1/app/helpers/thredded/application_helper.rb:30:in `thredded_page'", "/usr/local/rvm/gems/ruby-2.3.3/gems/thredded-0.12.1/app/views/thredded/private_topics/show.html.erb:6:in `__usr_local_rvm_gems_ruby_______gems_thredded________app_views_thredded_private_topics_show_html_erb___3032644149913108886_161061600'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/template.rb:145:in `block in render'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/template.rb:333:in `instrument'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/template.rb:143:in `render'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:52:in `render_template'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:14:in `render'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:46:in `render_template'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:27:in `render'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/rendering.rb:100:in `_render_template'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal/streaming.rb:217:in `_render_template'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/rendering.rb:83:in `render_to_body'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:32:in `render_to_body'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal/renderers.rb:37:in `render_to_body'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/abstract_controller/rendering.rb:25:in `render'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:16:in `render'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'", "/usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `ms'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `block in render'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:43:in `render'", "/usr/local/rvm/gems/ruby-2.3.3/gems/meta-tags-2.4.0/lib/meta_tags/controller_helper.rb:20:in `render'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:10:in `default_render'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:5:in `send_action'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:198:in `process_action'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:19:in `process_action'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal/rescue.rb:29:in `process_action'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:137:in `process'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionview-4.2.8/lib/action_view/rendering.rb:30:in `process'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal.rb:196:in `dispatch'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_controller/metal.rb:237:in `block in action'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:43:in `serve'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'", "/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/routing/mapper.rb:51:in `serve'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'", "/usr/local/rvm/gems/ruby-2.3.3/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'", "/usr/local/rvm/gems/ruby-2.3.3/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'", "/usr/local/rvm/gems/ruby-2.3.3/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'", "/usr/local/rvm/gems/ruby-2.3.3/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/omniauth-1.6.1/lib/omniauth/builder.rb:63:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'", "/usr/local/rvm/gems/ruby-2.3.3/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.5/lib/rack/etag.rb:24:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.5/lib/rack/conditionalget.rb:25:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/flash.rb:260:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.2.8/lib/active_record/query_cache.rb:36:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.2.8/lib/active_record/migration.rb:377:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:88:in `__run_callbacks__'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:73:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rollbar-2.14.0/lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rollbar-2.14.0/lib/rollbar.rb:145:in `scoped'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rollbar-2.14.0/lib/rollbar/middleware/rails/rollbar.rb:22:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rollbar-2.14.0/lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/chewy-0.9.0/lib/chewy/railtie.rb:17:in `block in call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/chewy-0.9.0/lib/chewy/strategy.rb:63:in `wrap'", "/usr/local/rvm/gems/ruby-2.3.3/gems/chewy-0.9.0/lib/chewy.rb:187:in `strategy'", "/usr/local/rvm/gems/ruby-2.3.3/gems/chewy-0.9.0/lib/chewy/railtie.rb:17:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'", "/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/rack/logger.rb:22:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/quiet_assets-1.1.0/lib/quiet_assets.rb:27:in `call_with_quiet_assets'", "/usr/local/rvm/gems/ruby-2.3.3/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.5/lib/rack/lock.rb:17:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/static.rb:120:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rack-utf8_sanitizer-1.3.2/lib/rack/utf8_sanitizer.rb:19:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.5/lib/rack/content_length.rb:15:in `call'", "/usr/local/rvm/gems/ruby-2.3.3/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'", "/usr/local/rvm/gems/ruby-2.3.3/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'", "/usr/local/rvm/gems/ruby-2.3.3/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'", "/usr/local/rvm/gems/ruby-2.3.3/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'", "/usr/local/rvm/gems/ruby-2.3.3/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'", "/usr/local/rvm/gems/ruby-2.3.3/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'", "/usr/local/rvm/gems/ruby-2.3.3/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'", "/usr/local/rvm/gems/ruby-2.3.3/gems/thin-1.5.1/lib/thin/backends/base.rb:63:in `start'", "/usr/local/rvm/gems/ruby-2.3.3/gems/thin-1.5.1/lib/thin/server.rb:159:in `start'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.5/lib/rack/handler/thin.rb:19:in `run'", "/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.5/lib/rack/server.rb:286:in `start'", "/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/commands/server.rb:80:in `start'", "/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:80:in `block in server'", "/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `tap'", "/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `server'", "/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'", "/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'", "bin/rails:9:in `require'", "bin/rails:9:in `<main>'"]
  Thredded::UserDetail Load (0.3ms)  SELECT  "thredded_user_details".* FROM "thredded_user_details" WHERE "thredded_user_details"."user_id" = $1 LIMIT 1  [["user_id", 6]]
  Rendered /usr/local/rvm/gems/ruby-2.3.3/gems/thredded-0.12.1/app/views/thredded/posts_common/actions/_quote.html.erb (12.0ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.3/gems/thredded-0.12.1/app/views/thredded/posts_common/actions/_edit.html.erb (10.1ms)
  Thredded::PrivatePost Load (0.2ms)  SELECT  "thredded_private_posts".* FROM "thredded_private_posts" WHERE "thredded_private_posts"."postable_id" = $1  ORDER BY "thredded_private_posts"."created_at" ASC, "thredded_private_posts"."id" ASC LIMIT 1  [["postable_id", 1]]
  Rendered /usr/local/rvm/gems/ruby-2.3.3/gems/thredded-0.12.1/app/views/thredded/posts_common/actions/_mark_as_unread.html.erb (6.3ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.3/gems/thredded-0.12.1/app/views/thredded/posts_common/_actions.html.erb (40.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.3/gems/thredded-0.12.1/app/views/thredded/users/_link.html.erb (0.6ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.3/gems/thredded-0.12.1/app/views/thredded/posts_common/_header.html.erb (9.4ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.3/gems/thredded-0.12.1/app/views/thredded/private_posts/_private_post.html.erb (59.1ms)
```

**Comment by glebm** [comment]
I cannot reproduce this. Are you using any logging gems or customizing Rails logging or subscription mechanism in any way?

**Comment by igorkasyanchuk** [comment]
Not sure, this is my Gemfile https://gist.github.com/igorkasyanchuk/f0cd14e0230837580015d1c3a45175fc
I guess nothing special
