### ISSUE TITLE
After bundle install - generate rake task failed

### ISSUE THREAD

**Issue by kchsieh** [thredded/thredded#602]
After I have included the thredded gem and did a bundle install.  When I try to get the available rake tasks (looking for the thredded:install), then got an error:

```
$ bundle exec rake -T
rake aborted!
SyntaxError: /Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/gems/onebox-1.8.13/lib/onebox/engine/amazon_onebox.rb:76: syntax error, unexpected '.'
        result[:description] = og[:description] || summary&.inner_text
                                                            ^
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/gems/onebox-1.8.13/lib/onebox/engine.rb:137:in `require_relative'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/gems/onebox-1.8.13/lib/onebox/engine.rb:137:in `<top (required)>'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/gems/onebox-1.8.13/lib/onebox.rb:55:in `require_relative'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/gems/onebox-1.8.13/lib/onebox.rb:55:in `<top (required)>'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/gems/thredded-0.13.1/lib/thredded/html_pipeline/onebox_filter.rb:3:in `<top (required)>'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/gems/thredded-0.13.1/lib/thredded.rb:22:in `<top (required)>'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/Users/kchsieh/RubymineProjects/api_central/config/application.rb:7:in `<top (required)>'
/Users/kchsieh/RubymineProjects/api_central/Rakefile:5:in `require'
/Users/kchsieh/RubymineProjects/api_central/Rakefile:5:in `<top (required)>'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/bin/bundle:23:in `load'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@global/bin/bundle:23:in `<main>'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/bin/ruby_executable_hooks:15:in `eval'
/Users/kchsieh/.rvm/gems/ruby-2.2.4@api-central/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

```

**Comment by glebm** [comment]
thredded_create_app requier Ruby 2.3+ https://github.com/thredded/thredded_create_app#pre-requisites

**Comment by glebm** [comment]
This is an issue in the onebox gem: https://github.com/discourse/onebox/pull/358#issuecomment-311684862

You can work around it by updating to ruby v2.3+
