### ISSUE TITLE
Small problem running with Heroku

### ISSUE THREAD

**Issue by EthanBogart** [thredded/thredded#631]
Hey, I used the thredded_create_app to initialize a thredded app. I try to deploy that app and unfortunately Heroku gives me `at=info method=GET path="/users/sign_in" host=myapp.herokuapp.com request_id=568e8db3-7ef5-48a0-a0fc-53d74e8e675a fwd="174.70.ipaddress" dyno=web.1 connect=0ms service=132ms status=500 bytes=1827 protocol=https`. I have been playing around with changing `sqlite3` to `pg` so that may be the problem but any help may be useful.

Thanks!

**Comment by glebm** [comment]
SQlite cannot be used on Heroku, because Heroku does not have a persistent filesystem. If you use thredded_create_app, it creates the app with Postgres by default, unless you tell it to use something else.

Please try re-creating the app, using Postgres this time.

Also have a look at the logs:

```bash
heroku logs -n 1500
```

**Comment by EthanBogart** [comment]
Thank you for the response @glebm! Unfortunately I get a problem trying to run thredded_create_app with postgres, which is why I am trying to migrate from sqlite3. 

In case you're curious, I get the error `PG::InvalidParameterValue: ERROR:  new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)
HINT:  Use the same encoding as in the template database, or use template0 as template.`

**Comment by glebm** [comment]
It's a problem with your Postgres installation. See: https://stackoverflow.com/a/16737776/181228

**Comment by EthanBogart** [comment]
I really appreciate the help! I got the new app running and it works fine on postgres locally. However, I still get the original error with the `status=500`. What do you think?

**Comment by glebm** [comment]
What's in the logs?

**Comment by EthanBogart** [comment]
It's a bit long but here is the info that comes before:

```
2017-10-17T20:39:54.167122+00:00 app[web.1]: I, [2017-10-17T20:39:54.167039 #34]  INFO -- : [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] Started GET "/users/sign_in" for 129.81.125.102 at 2017-10-17 20:39:54 +0000
2017-10-17T20:39:54.168259+00:00 app[web.1]: I, [2017-10-17T20:39:54.168182 #34]  INFO -- : [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] Processing by Devise::SessionsController#new as HTML
2017-10-17T20:39:54.174345+00:00 app[web.1]: I, [2017-10-17T20:39:54.174246 #34]  INFO -- : [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] Completed 500 Internal Server Error in 6ms (ActiveRecord: 3.6ms)
2017-10-17T20:39:54.176024+00:00 app[web.1]: F, [2017-10-17T20:39:54.175953 #34] FATAL -- : [9e2119d2-cacf-4a3f-95c0-95ed3e95560c]   
2017-10-17T20:39:54.176086+00:00 app[web.1]: F, [2017-10-17T20:39:54.176021 #34] FATAL -- : [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist
2017-10-17T20:39:54.176088+00:00 app[web.1]: LINE 8:                WHERE a.attrelid = '"users"'::regclass
2017-10-17T20:39:54.176089+00:00 app[web.1]:                                           ^
2017-10-17T20:39:54.176090+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2017-10-17T20:39:54.176090+00:00 app[web.1]:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
2017-10-17T20:39:54.176091+00:00 app[web.1]:                      c.collname, col_description(a.attrelid, a.attnum) AS comment
2017-10-17T20:39:54.176092+00:00 app[web.1]:                 FROM pg_attribute a
2017-10-17T20:39:54.176095+00:00 app[web.1]:                  AND a.attnum > 0 AND NOT a.attisdropped
2017-10-17T20:39:54.176096+00:00 app[web.1]:                ORDER BY a.attnum
2017-10-17T20:39:54.176097+00:00 app[web.1]: ):
2017-10-17T20:39:54.176177+00:00 app[web.1]: F, [2017-10-17T20:39:54.176077 #34] FATAL -- : [9e2119d2-cacf-4a3f-95c0-95ed3e95560c]   
2017-10-17T20:39:54.176365+00:00 app[web.1]: F, [2017-10-17T20:39:54.176216 #34] FATAL -- : [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:61:in `async_exec'
2017-10-17T20:39:54.176092+00:00 app[web.1]:                 LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2017-10-17T20:39:54.176368+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
2017-10-17T20:39:54.176093+00:00 app[web.1]:                 LEFT JOIN pg_type t ON a.atttypid = t.oid
2017-10-17T20:39:54.176369+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
2017-10-17T20:39:54.176094+00:00 app[web.1]:                 LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
2017-10-17T20:39:54.176370+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
2017-10-17T20:39:54.176095+00:00 app[web.1]:                WHERE a.attrelid = '"users"'::regclass
2017-10-17T20:39:54.176371+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:60:in `block in query'
2017-10-17T20:39:54.176372+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
2017-10-17T20:39:54.176380+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/model_schema.rb:471:in `load_schema!'
2017-10-17T20:39:54.176372+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
2017-10-17T20:39:54.176381+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/attributes.rb:233:in `load_schema!'
2017-10-17T20:39:54.176373+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
2017-10-17T20:39:54.176382+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/attribute_decorators.rb:50:in `load_schema!'
2017-10-17T20:39:54.176374+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
2017-10-17T20:39:54.176382+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/model_schema.rb:464:in `block in load_schema'
2017-10-17T20:39:54.176375+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
2017-10-17T20:39:54.176383+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
2017-10-17T20:39:54.176367+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:61:in `block (2 levels) in query'
2017-10-17T20:39:54.176375+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:59:in `query'
2017-10-17T20:39:54.176376+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:763:in `column_definitions'
2017-10-17T20:39:54.176384+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/model_schema.rb:461:in `load_schema'
2017-10-17T20:39:54.176377+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:166:in `columns'
2017-10-17T20:39:54.176385+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/model_schema.rb:353:in `attribute_types'
2017-10-17T20:39:54.176390+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/devise-4.3.0/app/controllers/devise/sessions_controller.rb:9:in `new'
2017-10-17T20:39:54.176391+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/abstract_controller/base.rb:186:in `process_action'
2017-10-17T20:39:54.176391+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
2017-10-17T20:39:54.176378+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/schema_cache.rb:67:in `columns'
2017-10-17T20:39:54.176385+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/attribute_methods.rb:179:in `has_attribute?'
2017-10-17T20:39:54.176379+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/schema_cache.rb:73:in `columns_hash'
2017-10-17T20:39:54.176386+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/inheritance.rb:55:in `new'
2017-10-17T20:39:54.176392+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_controller/metal/rendering.rb:30:in `process_action'
2017-10-17T20:39:54.176393+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
2017-10-17T20:39:54.176393+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
2017-10-17T20:39:54.176394+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
2017-10-17T20:39:54.176395+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_controller/metal/rescue.rb:20:in `process_action'
2017-10-17T20:39:54.176396+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
2017-10-17T20:39:54.176396+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `block in instrument'
2017-10-17T20:39:54.176397+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
2017-10-17T20:39:54.176398+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `instrument'
2017-10-17T20:39:54.176399+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
2017-10-17T20:39:54.176399+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
2017-10-17T20:39:54.176400+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.4/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
2017-10-17T20:39:54.176401+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/abstract_controller/base.rb:124:in `process'
2017-10-17T20:39:54.176401+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionview-5.1.4/lib/action_view/rendering.rb:30:in `process'
2017-10-17T20:39:54.176402+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_controller/metal.rb:189:in `dispatch'
2017-10-17T20:39:54.176403+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_controller/metal.rb:253:in `dispatch'
2017-10-17T20:39:54.176403+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
2017-10-17T20:39:54.176404+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:31:in `serve'
2017-10-17T20:39:54.176405+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
2017-10-17T20:39:54.176406+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:46:in `serve'
2017-10-17T20:39:54.176407+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:50:in `block in serve'
2017-10-17T20:39:54.176407+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:33:in `each'
2017-10-17T20:39:54.176408+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:33:in `serve'
2017-10-17T20:39:54.176409+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:834:in `call'
2017-10-17T20:39:54.176410+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
2017-10-17T20:39:54.176413+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
2017-10-17T20:39:54.176414+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
2017-10-17T20:39:54.176415+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
2017-10-17T20:39:54.176415+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
2017-10-17T20:39:54.176417+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
2017-10-17T20:39:54.176416+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
2017-10-17T20:39:54.176417+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
2017-10-17T20:39:54.176418+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/cookies.rb:613:in `call'
2017-10-17T20:39:54.176419+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
2017-10-17T20:39:54.176420+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:97:in `run_callbacks'
2017-10-17T20:39:54.176421+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
2017-10-17T20:39:54.176420+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
2017-10-17T20:39:54.176422+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
2017-10-17T20:39:54.176422+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/rack/logger.rb:36:in `call_app'
2017-10-17T20:39:54.176423+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/rack/logger.rb:24:in `block in call'
2017-10-17T20:39:54.176424+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:69:in `block in tagged'
2017-10-17T20:39:54.176425+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:26:in `tagged'
2017-10-17T20:39:54.176425+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:69:in `tagged'
2017-10-17T20:39:54.176426+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/rack/logger.rb:24:in `call'
2017-10-17T20:39:54.176427+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
2017-10-17T20:39:54.176427+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
2017-10-17T20:39:54.176428+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/request_id.rb:25:in `call'
2017-10-17T20:39:54.176429+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
2017-10-17T20:39:54.176429+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
2017-10-17T20:39:54.176430+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
2017-10-17T20:39:54.176431+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
2017-10-17T20:39:54.176431+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/static.rb:125:in `call'
2017-10-17T20:39:54.176432+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
2017-10-17T20:39:54.176433+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/engine.rb:522:in `call'
2017-10-17T20:39:54.176433+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
2017-10-17T20:39:54.176437+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
2017-10-17T20:39:54.176437+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
2017-10-17T20:39:54.176438+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
2017-10-17T20:39:54.176439+00:00 app[web.1]: [9e2119d2-cacf-4a3f-95c0-95ed3e95560c] vendor/bundle/ruby/2.3.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

It seems like more problems with the Active Record

**Comment by glebm** [comment]
Perhaps you didn't run:

```
heroku run rake db:migrate db:seed
```

**Comment by EthanBogart** [comment]
After a couple hours of figuring out which commands do and do not work through Heroku CLI, I got it to work. Thank you!
