### ISSUE TITLE
dealing with column name when it does not exist

### ISSUE THREAD

**Issue by hopewise** [thredded/thredded#655]
In my `User` model I have a method named `name` which gets the name for an associated table `basic_profile` as:

    def name
        fullname
    end

however, I don't have a column `name` in the users table, this caused an issue as below, how would I solve this? isn't having a method `name` at user model sufficient?

```
RuntimeError: Column "name" not found on table "users"
  from db_text_search/case_insensitive.rb:94:in `column_case_sensitive?'
  from db_text_search/case_insensitive.rb:74:in `block in adapter_class'
  from db_text_search.rb:28:in `call'
  from db_text_search.rb:28:in `match_adapter'
  from db_text_search/case_insensitive.rb:76:in `adapter_class'
  from db_text_search/case_insensitive.rb:13:in `initialize'
  from thredded/post_common.rb:46:in `new'
  from thredded/post_common.rb:46:in `readers_from_user_names'
  from thredded/at_notification_extractor.rb:19:in `block in run'
  from thredded/html_pipeline/at_mention_filter.rb:33:in `call'
  from thredded/html_pipeline/at_mention_filter.rb:33:in `mentioned_users'
  from thredded/at_notification_extractor.rb:20:in `run'
  from thredded/autofollow_users.rb:17:in `mentioned_users'
  from thredded/autofollow_users.rb:24:in `new_followers'
  from thredded/autofollow_users.rb:10:in `run'
  from thredded/auto_follow_and_notify_job.rb:10:in `perform'
  from active_job/execution.rb:32:in `block in perform_now'
  from active_support/callbacks.rb:117:in `call'
  from active_support/callbacks.rb:117:in `call'
  from active_support/callbacks.rb:555:in `block (2 levels) in compile'
  from active_support/callbacks.rb:505:in `call'
  from active_support/callbacks.rb:505:in `call'
  from active_support/callbacks.rb:498:in `block (2 levels) in around'
  from active_support/callbacks.rb:343:in `call'
  from active_support/callbacks.rb:343:in `block (2 levels) in simple'
  from new_relic/agent/transaction.rb:105:in `wrap'
  from new_relic/agent/instrumentation/active_job.rb:63:in `run_in_transaction'
  from new_relic/agent/instrumentation/active_job.rb:52:in `perform'
  from new_relic/agent/instrumentation/active_job.rb:22:in `block (3 levels) in <top (required)>'
  from active_support/callbacks.rb:441:in `instance_exec'
  from active_support/callbacks.rb:441:in `block in make_lambda'
  from active_support/callbacks.rb:342:in `call'
  from active_support/callbacks.rb:342:in `block in simple'
  from active_support/callbacks.rb:497:in `call'
  from active_support/callbacks.rb:497:in `block in around'
  from active_support/callbacks.rb:505:in `call'
  from active_support/callbacks.rb:505:in `call'
  from active_support/callbacks.rb:498:in `block (2 levels) in around'
  from active_support/callbacks.rb:343:in `call'
  from active_support/callbacks.rb:343:in `block (2 levels) in simple'
  from raven/integrations/rails/active_job.rb:18:in `call'
  from raven/integrations/rails/active_job.rb:18:in `capture_and_reraise_with_sentry'
  from raven/integrations/rails/active_job.rb:12:in `block (2 levels) in included'
  from active_support/callbacks.rb:441:in `instance_exec'
  from active_support/callbacks.rb:441:in `block in make_lambda'
  from active_support/callbacks.rb:342:in `call'
  from active_support/callbacks.rb:342:in `block in simple'
  from active_support/callbacks.rb:497:in `call'
  from active_support/callbacks.rb:497:in `block in around'
  from active_support/callbacks.rb:505:in `call'
  from active_support/callbacks.rb:505:in `call'
  from active_support/callbacks.rb:498:in `block (2 levels) in around'
  from active_support/callbacks.rb:343:in `call'
  from active_support/callbacks.rb:343:in `block (2 levels) in simple'
  from i18n.rb:265:in `with_locale'
  from active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
  from active_support/callbacks.rb:441:in `instance_exec'
  from active_support/callbacks.rb:441:in `block in make_lambda'
  from active_support/callbacks.rb:342:in `call'
  from active_support/callbacks.rb:342:in `block in simple'
  from active_support/callbacks.rb:497:in `call'
  from active_support/callbacks.rb:497:in `block in around'
  from active_support/callbacks.rb:505:in `call'
  from active_support/callbacks.rb:505:in `call'
  from active_support/callbacks.rb:498:in `block (2 levels) in around'
  from active_support/callbacks.rb:343:in `call'
  from active_support/callbacks.rb:343:in `block (2 levels) in simple'
  from active_job/logging.rb:23:in `call'
  from active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
  from active_support/notifications.rb:164:in `block in instrument'
  from active_support/notifications/instrumenter.rb:20:in `instrument'
  from active_support/notifications.rb:164:in `instrument'
  from active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
  from active_job/logging.rb:43:in `block in tag_logger'
  from active_support/tagged_logging.rb:68:in `block in tagged'
  from active_support/tagged_logging.rb:26:in `tagged'
  from active_support/tagged_logging.rb:68:in `tagged'
  from active_job/logging.rb:43:in `tag_logger'
  from active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
  from active_support/callbacks.rb:441:in `instance_exec'
  from active_support/callbacks.rb:441:in `block in make_lambda'
  from active_support/callbacks.rb:342:in `call'
  from active_support/callbacks.rb:342:in `block in simple'
  from active_support/callbacks.rb:497:in `call'
  from active_support/callbacks.rb:497:in `block in around'
  from active_support/callbacks.rb:505:in `call'
  from active_support/callbacks.rb:505:in `call'
  from active_support/callbacks.rb:92:in `__run_callbacks__'
  from active_support/callbacks.rb:778:in `_run_perform_callbacks'
  from active_support/callbacks.rb:81:in `run_callbacks'
  from active_job/execution.rb:31:in `perform_now'
  from active_job/execution.rb:21:in `execute'
  from active_job/queue_adapters/sucker_punch_adapter.rb:35:in `perform'
  from sucker_punch/job.rb:54:in `__run_perform'
  from sucker_punch/job.rb:36:in `block in perform_async'
  from concurrent/executor/ruby_thread_pool_executor.rb:348:in `call'
  from concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
  from concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
  from concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
  from concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
  from concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
  from concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by glebm** [comment]
Unfortunately, Thredded does require a column on the user (its name is configurable but it has to be a column). The column is used for @-mention autocomplete etc.

**Comment by hopewise** [comment]
But, where are all the places where `Thredded ` access `name` column, if I want to try specifying a user search relation? as I will need to update all those places..

**Comment by glebm** [comment]
It is always referenced as `Thredded.user_name_column`.

**Comment by glebm** [comment]
Closed due to inactivity.
