### ISSUE TITLE
Undefined method page

### ISSUE THREAD

**Issue by leenyburger** [thredded/thredded#741]
Everything was working great at Rails 4.2, and we recently upgraded to Rails 5.2. I also upgraded the thredded gem to 0.16.0 and ran the migration as specified in the release notes. 
From the main thredded page, when a user clicks on a specific messageboard I get the following error: 
`Undefined method page for #<Thredded::Messageboard:0x007fb92bcd4100>`
The error points to `topics_controller#index`
If I put a debugger at the start of the method: 
`/thredded/topics_controller.rb`
``` 
def index
      byebug
      page_scope = policy_scope(messageboard.topics)
        .order_sticky_first.order_recently_posted_first
        .includes(:categories, :last_user, :user)
        .page(current_page)
```

When running rails 4.2 I can do the following: 

```
(byebug) policy_scope(messageboard.topics).page(current_page)
  Thredded::Topic Load (0.5ms)  SELECT  "thredded_topics".* FROM "thredded_topics" WHERE "thredded_topics"."messageboard_id" = $1 AND (("thredded_topics"."moderation_state" != 2 OR "thredded_topics"."user_id" = 2) OR "thredded_topics"."messageboard_id" IN (19, 20, 21, 22, 23, 24, 25, 26, 27, 28)) LIMIT 20 OFFSET 0  [["messageboard_id", 19]]
#<ActiveRecord::AssociationRelation []>
```
With Rails 5.2 this happens: 
```
(byebug) policy_scope(messageboard.topics).page(current_page)
  Thredded::Topic Load (1.8ms)  SELECT  "thredded_topics".* FROM "thredded_topics" WHERE "thredded_topics"."messageboard_id" = $1 LIMIT $2  [["messageboard_id", 19], ["LIMIT", 11]]
*** NoMethodError Exception: undefined method `page' for #<ActiveRecord::AssociationRelation []>
```

Full backtrace: 
```
Started GET "/communities/sift-local-community-board-all-things-considered" for 127.0.0.1 at 2018-10-07 11:47:04 -0400
Processing by Thredded::TopicsController#index as HTML
  Parameters: {"messageboard_id"=>"sift-local-community-board-all-things-considered"}
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 2], ["LIMIT", 1]]
  Profile Load (0.7ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."user_id" = $1 LIMIT $2  [["user_id", 2], ["LIMIT", 1]]
  Thredded::Messageboard Load (0.5ms)  SELECT  "thredded_messageboards".* FROM "thredded_messageboards" WHERE "thredded_messageboards"."slug" = $1 LIMIT $2  [["slug", "sift-local-community-board-all-things-considered"], ["LIMIT", 1]]
  Thredded::Topic Load (0.6ms)  SELECT  "thredded_topics".* FROM "thredded_topics" WHERE "thredded_topics"."messageboard_id" = $1 ORDER BY "thredded_topics"."sticky" DESC, "thredded_topics"."last_post_at" DESC, "thredded_topics"."id" DESC LIMIT $2  [["messageboard_id", 19], ["LIMIT", 11]]
Completed 500 Internal Server Error in 19ms (ActiveRecord: 1.8ms)


  
  CACHE Thredded::Topic Load (0.0ms)  SELECT  "thredded_topics".* FROM "thredded_topics" WHERE "thredded_topics"."messageboard_id" = $1 ORDER BY "thredded_topics"."sticky" DESC, "thredded_topics"."last_post_at" DESC, "thredded_topics"."id" DESC LIMIT $2  [["messageboard_id", 19], ["LIMIT", 11]]
NoMethodError (undefined method `page' for #<ActiveRecord::AssociationRelation []>):
  
activerecord (5.2.1) lib/active_record/relation/delegation.rb:95:in `method_missing'
thredded (0.16.0) app/controllers/thredded/topics_controller.rb:26:in `index'
actionpack (5.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.1) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.1) lib/active_support/callbacks.rb:109:in `block in run_callbacks'
public_activity (1.6.2) lib/public_activity/utility/store_controller.rb:25:in `store_controller_for_public_activity'
activesupport (5.2.1) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
react-rails (2.4.7) lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
activesupport (5.2.1) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
activesupport (5.2.1) lib/active_support/callbacks.rb:136:in `run_callbacks'
actionpack (5.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.1) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.1) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
railties (5.2.1) lib/rails/engine.rb:524:in `call'
railties (5.2.1) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.1) lib/rails/railtie.rb:190:in `method_missing'
actionpack (5.2.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (5.2.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack-pjax (1.0.0) lib/rack/pjax.rb:12:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
bullet (5.7.6) lib/bullet/rack.rb:14:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
warden-jwt_auth (0.1.3) lib/warden/jwt_auth/middleware/token_dispatcher.rb:20:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
warden-jwt_auth (0.1.3) lib/warden/jwt_auth/middleware/revocation_manager.rb:20:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.5) lib/rack/builder.rb:153:in `call'
warden-jwt_auth (0.1.3) lib/warden/jwt_auth/middleware.rb:23:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
remotipart (1.4.2) lib/remotipart/middleware.rb:32:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.5) lib/rack/tempfile_reaper.rb:15:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.5) lib/rack/etag.rb:25:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.5) lib/rack/head.rb:12:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
activerecord (5.2.1) lib/active_record/migration.rb:559:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
activesupport (5.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
dragonfly (1.1.5) lib/dragonfly/cookie_monster.rb:9:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
webpacker (3.5.5) lib/webpacker/dev_server_proxy.rb:22:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
railties (5.2.1) lib/rails/engine.rb:524:in `call'
newrelic_rpm (5.4.0.347) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'

93 94 95 96 97 98 | arel.public_send(method, *args, &block)           else             super           end         end     end
-- | --



93 94 95 96 97 98 | arel.public_send(method, *args, &block)           else             super           end         end     end
-- | --
```

**Comment by jayroh** [comment]
What version of Kaminari is being used between the 4.2 and 5.2 branches?

**Comment by leenyburger** [comment]
Yes, both are using 1.1.1. We have a custom initializer for Kaminari: 
```
Kaminari.configure do |config|
  config.page_method_name = :by_page
end
```

**Comment by jayroh** [comment]
Well that's probably why then.

You'll either have to monkey-patch thredded or change your config.

**Comment by glebm** [comment]
Alternatively, submit a PR that replaces `page` with `send(Kaminari.page_method_name)`!

**Comment by jayroh** [comment]
Oooooor that ☝️😁 !
