### ISSUE TITLE
500 on /forum/admin/moderation

### ISSUE THREAD

**Issue by hlambeth** [thredded/thredded#794]
Hi all,
I'm currently configuring the thredded gem on Rails Version: 4.2.11 and everything works great except for the moderation page. I currently have both the admin and moderator_column configured in the thredded.rb file to use the same boolean and the admin works fine. Any ideas on what the issue might be with the moderation page?

**thredded.rb**
```
Thredded.user_class = 'User'
Thredded.user_name_column = :slug

Thredded.user_path = ->(user) {
  # user_path = :"#{Thredded.user_class_name.demodulize.underscore}_path"
  # main_app.respond_to?(user_path) ? main_app.send(user_path, user) : "/users/#{user.to_param}"
  nil
}

Thredded.current_user_method = :"current_#{Thredded.user_class_name.demodulize.underscore}"
Thredded.avatar_url = ->(user) { Gravatar.src(user.email, 156, 'mm') }

# ==> Permissions Configuration
Thredded.moderator_column = :data_admin
Thredded.admin_column = :data_admin
Thredded.content_visible_while_pending_moderation = true

# ==> UI configuration
Thredded.show_topic_followers = false

Thredded.currently_online_enabled = true

Thredded.private_messaging_enabled = true

Thredded.layout = 'layouts/pro_with_sidebar'

# ==> Email Configuration
Thredded.email_from = 'forum@everfest.com'
Thredded.email_outgoing_prefix = '[Everfest Forum] '
Thredded.parent_mailer = 'ActionMailer::Base'
```

**Here is the full stack trace of the error.**
```I, [2019-02-27T12:29:40.608326 #12643]  INFO -- : Completed 500 Internal Server Error in 973ms (ActiveRecord: 42.0ms)
F, [2019-02-27T12:29:40.639474 #12643] FATAL -- : 
NoMethodError - undefined method `map' for #<Class:0x00007feab89fb5a0>
Did you mean?  map_dir
               max_pages
               max_per_page
               max_pages_per
               max_paginates_per
               tap:
  activerecord (4.2.11) lib/active_record/dynamic_matchers.rb:26:in `method_missing'
  thredded (0.16.8) app/models/concerns/thredded/post_common.rb:24:in `block (2 levels) in <module:PostCommon>'
  activerecord (4.2.11) lib/active_record/scoping/named.rb:155:in `block (2 levels) in scope'
  activerecord (4.2.11) lib/active_record/relation.rb:302:in `scoping'
  activerecord (4.2.11) lib/active_record/scoping/named.rb:155:in `block in scope'
  activerecord (4.2.11) lib/active_record/relation/delegation.rb:94:in `block in method_missing'
  activerecord (4.2.11) lib/active_record/relation.rb:302:in `scoping'
  activerecord (4.2.11) lib/active_record/relation/delegation.rb:94:in `method_missing'
  thredded (0.16.8) app/controllers/thredded/moderation_controller.rb:13:in `pending'
  actionpack (4.2.11) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.11) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.11) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.11) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.11) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.11) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.11) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.11) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.11) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.11) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.11) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.11) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.11) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.11) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.11) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.11) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.11) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.11) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  searchkick (2.3.1) lib/searchkick/logging.rb:209:in `process_action'
  activerecord (4.2.11) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.11) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.11) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.11) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.11) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.11) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.11) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.11) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.11) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.11) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.11) lib/action_dispatch/routing/route_set.rb:817:in `call'
  railties (4.2.11) lib/rails/engine.rb:518:in `call'
  railties (4.2.11) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.11) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.11) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.11) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.11) lib/action_dispatch/routing/route_set.rb:817:in `call'
  omniauth (1.6.1) lib/omniauth/strategy.rb:189:in `call!'
  omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
  rack-pjax (0.8.0) lib/rack/pjax.rb:12:in `call'
  bullet (5.6.1) lib/bullet/rack.rb:12:in `call'
  meta_request (0.4.3) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.4.3) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  i18n-js (3.0.1) lib/i18n/js/middleware.rb:14:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  rack (1.6.11) lib/rack/etag.rb:24:in `call'
  rack (1.6.11) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.11) lib/rack/head.rb:13:in `call'
  remotipart (1.3.1) lib/remotipart/middleware.rb:32:in `call'
  actionpack (4.2.11) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.11) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.11) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.11) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.11) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.11) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.11) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.11) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.11) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.11) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.11) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.11) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.11) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.11) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.11) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.3.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.3.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.3.0) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.11) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  rack-contrib (1.5.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.4.3) lib/meta_request/middlewares/headers.rb:16:in `call'
  actionpack (4.2.11) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.11) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.11) lib/rails/rack/logger.rb:22:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.11) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.11) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.11) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.11) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.11) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.11) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.11) lib/rack/sendfile.rb:113:in `call'
  honeybadger (2.7.2) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
  honeybadger (2.7.2) lib/honeybadger/config.rb:192:in `with_request'
  honeybadger (2.7.2) lib/honeybadger/rack/error_notifier.rb:30:in `call'
  honeybadger (2.7.2) lib/honeybadger/rack/user_feedback.rb:28:in `call'
  honeybadger (2.7.2) lib/honeybadger/rack/user_informer.rb:18:in `call'
  railties (4.2.11) lib/rails/engine.rb:518:in `call'
  railties (4.2.11) lib/rails/application.rb:165:in `call'
  rack (1.6.11) lib/rack/content_length.rb:15:in `call'
  thin (1.7.2) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.7.2) lib/thin/connection.rb:84:in `pre_process'
  thin (1.7.2) lib/thin/connection.rb:53:in `process'
  thin (1.7.2) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.2.5) lib/eventmachine.rb:194:in `run'
  thin (1.7.2) lib/thin/backends/base.rb:73:in `start'
  thin (1.7.2) lib/thin/server.rb:162:in `start'
  rack (1.6.11) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.11) lib/rack/server.rb:287:in `start'
  railties (4.2.11) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.11) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.11) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.11) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.11) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:8:in `<top (required)>'
  spring (1.7.2) lib/spring/client/rails.rb:28:in `call'
  spring (1.7.2) lib/spring/client/command.rb:7:in `call'
  spring (1.7.2) lib/spring/client.rb:30:in `run'
  spring (1.7.2) bin/spring:49:in `<top (required)>'
  spring (1.7.2) lib/spring/binstub.rb:11:in `<top (required)>'
  bin/spring:13:in `<top (required)>'
  bin/rails:3:in `<main>'
```

**Comment by CD1212** [comment]
I'm getting the exact same error on a fresh install of thredded into an existing Rails app

**Comment by glebm** [comment]
v0.16.9 released with a fix (y'all should really update to Rails 5+, as Rails 4 doesn't even receive security fixes anymore)

**Comment by hlambeth** [comment]
Hey Gleb, thank you so much for the quick response! As for updating I would love to be on rails 5, and I have suggested several times that we upgrade at work. Unfortunately, I haven't been able to get management to sign off yet, but hopefully soon 🤞 . Thanks again!
