### ISSUE TITLE
ActiveRecord::RecordNotUnique for "thredded_user_topic_read_states_user_postable"

### ISSUE THREAD

**Issue by fosterfarrell9** [thredded/thredded#845]
We've been using thredded a while now, without any issues. It's an awesome engine. In the last weeks, however, we have occasionally seen exceptions caused by thredded in our log files. These exceptions are always of the same type, see the sttack trace below. We cannot reproduce the exceptions.
We use Rails 6.0.1, Ruby 2.6.5 with a PG database, the configuration of thredded is pretty much standard. Any help would be appreciated.

```
F, [2019-11-20T22:09:08.172516 #1] FATAL -- : [cdb29101-39c1-4b38-ac18-ab75746706f7]   
[cdb29101-39c1-4b38-ac18-ab75746706f7] ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "thredded_user_topic_read_states_user_postable"
DETAIL:  Key (user_id, postable_id)=(1808, 36) already exists.
):
[cdb29101-39c1-4b38-ac18-ab75746706f7]   
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `async_exec_params'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `block (2 levels) in exec_no_cache'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `block in exec_no_cache'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/abstract_adapter.rb:718:in `block (2 levels) in log'
[cdb29101-39c1-4b38-ac18-ab75746706f7] /usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/abstract_adapter.rb:717:in `block in log'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/abstract_adapter.rb:708:in `log'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/postgresql_adapter.rb:670:in `exec_no_cache'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/postgresql_adapter.rb:653:in `execute_and_clear'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `exec_query'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:135:in `exec_insert'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:132:in `exec_insert'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:166:in `insert'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `insert'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/persistence.rb:375:in `_insert_record'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/persistence.rb:933:in `_create_record'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/counter_cache.rb:163:in `_create_record'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/locking/optimistic.rb:70:in `_create_record'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/attribute_methods/dirty.rb:211:in `_create_record'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/callbacks.rb:332:in `block in _create_record'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/callbacks.rb:827:in `_run_create_callbacks'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/callbacks.rb:332:in `_create_record'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/timestamp.rb:111:in `_create_record'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/persistence.rb:906:in `create_or_update'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/callbacks.rb:328:in `block in create_or_update'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/callbacks.rb:135:in `run_callbacks'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/callbacks.rb:328:in `create_or_update'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/timestamp.rb:129:in `create_or_update'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/persistence.rb:503:in `save!'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/validations.rb:53:in `save!'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/transactions.rb:319:in `block in save!'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:279:in `transaction'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/transactions.rb:212:in `transaction'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/transactions.rb:319:in `save!'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/suppressor.rb:48:in `save!'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/persistence.rb:635:in `block in update!'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `block in transaction'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
[cdb29101-39c1-4b38-ac18-ab75746706f7] /usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/transactions.rb:212:in `transaction'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/persistence.rb:633:in `update!'
[cdb29101-39c1-4b38-ac18-ab75746706f7] thredded (0.16.14) app/models/thredded/user_topic_read_state.rb:33:in `touch!'
[cdb29101-39c1-4b38-ac18-ab75746706f7] thredded (0.16.14) app/controllers/thredded/topics_controller.rb:63:in `show'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/abstract_controller/base.rb:196:in `process_action'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/callbacks.rb:135:in `run_callbacks'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/notifications.rb:180:in `block in instrument'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/notifications.rb:180:in `instrument'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activerecord (6.0.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/abstract_controller/base.rb:136:in `process'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionview (6.0.1) lib/action_view/rendering.rb:39:in `process'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_controller/metal.rb:191:in `dispatch'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_controller/metal.rb:252:in `dispatch'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/journey/router.rb:32:in `each'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/journey/router.rb:32:in `serve'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/routing/route_set.rb:837:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] railties (6.0.1) lib/rails/engine.rb:526:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] railties (6.0.1) lib/rails/railtie.rb:190:in `public_send'
[cdb29101-39c1-4b38-ac18-ab75746706f7] railties (6.0.1) lib/rails/railtie.rb:190:in `method_missing'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/journey/router.rb:32:in `each'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/journey/router.rb:32:in `serve'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/routing/route_set.rb:837:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] warden (1.2.8) lib/warden/manager.rb:34:in `catch'
[cdb29101-39c1-4b38-ac18-ab75746706f7] warden (1.2.8) lib/warden/manager.rb:34:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] rack (2.0.7) lib/rack/etag.rb:25:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] rack (2.0.7) lib/rack/head.rb:12:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
[cdb29101-39c1-4b38-ac18-ab75746706f7] rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/middleware/cookies.rb:648:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] railties (6.0.1) lib/rails/rack/logger.rb:38:in `call_app'
[cdb29101-39c1-4b38-ac18-ab75746706f7] railties (6.0.1) lib/rails/rack/logger.rb:26:in `block in call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/tagged_logging.rb:28:in `tagged'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/tagged_logging.rb:80:in `tagged'
[cdb29101-39c1-4b38-ac18-ab75746706f7] railties (6.0.1) lib/rails/rack/logger.rb:26:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] rack (2.0.7) lib/rack/method_override.rb:22:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] rack (2.0.7) lib/rack/runtime.rb:22:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] activesupport (6.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/middleware/static.rb:126:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] actionpack (6.0.1) lib/action_dispatch/middleware/host_authorization.rb:77:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] railties (6.0.1) lib/rails/engine.rb:526:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] puma (3.12.1) lib/puma/configuration.rb:227:in `call'
[cdb29101-39c1-4b38-ac18-ab75746706f7] puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
[cdb29101-39c1-4b38-ac18-ab75746706f7] puma (3.12.1) lib/puma/server.rb:474:in `process_client'
[cdb29101-39c1-4b38-ac18-ab75746706f7] puma (3.12.1) lib/puma/server.rb:334:in `block in run'
[cdb29101-39c1-4b38-ac18-ab75746706f7] puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by glebm** [comment]
Seems like a race condition.

We work around similar race conditions as follows:
https://github.com/thredded/thredded/blob/79bef719a4212ae9efd13ce1885cd3eb5c2a5973/app/jobs/thredded/activity_updater_job.rb#L10-L16

To fix this, send a PR doing a similar thing in the following places:

https://github.com/thredded/thredded/blob/79bef719a4212ae9efd13ce1885cd3eb5c2a5973/app/models/thredded/user_topic_read_state.rb#L29
https://github.com/thredded/thredded/blob/79bef719a4212ae9efd13ce1885cd3eb5c2a5973/app/models/thredded/user_private_topic_read_state.rb#L26

**Comment by glebm** [comment]
Now try running from master to see if this has solved the issue!

**Comment by fosterfarrell9** [comment]
No more exceptions in the last two days. So I think the issue can be closed.
