### ISSUE TITLE
Rails 6.0.2.rc1 compatibility

### ISSUE THREAD

**Issue by fosterfarrell9** [thredded/thredded#847]
We're having some problems upgrading to Rails 6.0.2.rc1 which seem to be caused by thredded (of course, it might be a Rails bug as well).

To reproduce, set up a plain new Rails app in Rails 6.0.1, add the thredded gem (or you use [this repository](https://github.com/fosterfarrell9/thredded_with_rails6.0.2.rc1) for that purpose) and then upgrade to Rails 6.0.2.rc1. Starting the rails server results in an exception that appears to be caused by thredded routing:

```
=> Booting Puma
=> Rails 6.0.2.rc1 application starting in development
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
        92: from bin/rails:4:in `<main>'
        91: from /home/denis/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.rc1/lib/active_support/dependencies.rb:325:in `require'
        90: from /home/denis/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.rc1/lib/active_support/dependencies.rb:291:in `load_dependency'
        89: from /home/denis/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.rc1/lib/active_support/dependencies.rb:325:in `block in require'
        88: from /home/denis/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        87: from /home/denis/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        86: from /home/denis/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        85: from /home/denis/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        84: from /home/denis/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
        83: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/commands.rb:18:in `<main>'
        82: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/command.rb:46:in `invoke'
        81: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/command/base.rb:69:in `perform'
        80: from /home/denis/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        79: from /home/denis/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        78: from /home/denis/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        77: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/commands/server/server_command.rb:138:in `perform'
        76: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/commands/server/server_command.rb:138:in `tap'
        75: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        74: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/commands/server/server_command.rb:37:in `start'
        73: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
        72: from /home/denis/.rvm/gems/ruby-2.6.5/gems/rack-2.0.7/lib/rack/server.rb:354:in `wrapped_app'
        71: from /home/denis/.rvm/gems/ruby-2.6.5/gems/rack-2.0.7/lib/rack/server.rb:219:in `app'
        70: from /home/denis/.rvm/gems/ruby-2.6.5/gems/rack-2.0.7/lib/rack/server.rb:319:in `build_app_and_options_from_config'
        69: from /home/denis/.rvm/gems/ruby-2.6.5/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
        68: from /home/denis/.rvm/gems/ruby-2.6.5/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
        67: from /home/denis/.rvm/gems/ruby-2.6.5/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
        66: from config.ru:in `<main>'
        65: from config.ru:in `new'
        64: from /home/denis/.rvm/gems/ruby-2.6.5/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
        63: from /home/denis/.rvm/gems/ruby-2.6.5/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
        62: from config.ru:3:in `block in <main>'
        61: from /home/denis/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
        60: from /home/denis/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.rc1/lib/active_support/dependencies.rb:325:in `require'
        59: from /home/denis/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.rc1/lib/active_support/dependencies.rb:291:in `load_dependency'
        58: from /home/denis/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.rc1/lib/active_support/dependencies.rb:325:in `block in require'
        57: from /home/denis/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
        56: from /home/denis/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        55: from /home/denis/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        54: from /home/denis/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        53: from /home/denis/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        52: from /home/denis/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
        51: from /mnt/d/Rails/thredded_with_rails6.0.2.rc1/config/environment.rb:5:in `<main>'
        50: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/application.rb:363:in `initialize!'
        49: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/initializable.rb:60:in `run_initializers'
        48: from /home/denis/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        47: from /home/denis/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        46: from /home/denis/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        45: from /home/denis/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `call'
        44: from /home/denis/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each'
        43: from /home/denis/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        42: from /home/denis/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        41: from /home/denis/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        40: from /home/denis/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        39: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/initializable.rb:61:in `block in run_initializers'
        38: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/initializable.rb:32:in `run'
        37: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/initializable.rb:32:in `instance_exec'
        36: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/application/finisher.rb:184:in `block in <module:Finisher>'
        35: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:10:in `execute'
        34: from /home/denis/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.rc1/lib/active_support/file_update_checker.rb:83:in `execute'
        33: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:30:in `block in updater'
        32: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:20:in `reload!'
        31: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:41:in `load_paths'
        30: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:41:in `each'
        29: from /home/denis/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:41:in `block in load_paths'
        28: from /home/denis/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
        27: from /home/denis/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
        26: from /home/denis/.rvm/gems/ruby-2.6.5/bundler/gems/thredded-3f60a57c8c16/config/routes.rb:3:in `<main>'
        25: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/route_set.rb:411:in `draw'
        24: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/route_set.rb:427:in `eval_block'
        23: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:648:in `with_default_scope'
        22: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:887:in `scope'
        21: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:649:in `block in with_default_scope'
        20: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:649:in `instance_exec'
        19: from /home/denis/.rvm/gems/ruby-2.6.5/bundler/gems/thredded-3f60a57c8c16/config/routes.rb:39:in `block in <main>'
        18: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:887:in `scope'
        17: from /home/denis/.rvm/gems/ruby-2.6.5/bundler/gems/thredded-3f60a57c8c16/config/routes.rb:41:in `block (2 levels) in <main>'
        16: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:887:in `scope'
        15: from /home/denis/.rvm/gems/ruby-2.6.5/bundler/gems/thredded-3f60a57c8c16/config/routes.rb:42:in `block (3 levels) in <main>'
        14: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:887:in `scope'
        13: from /home/denis/.rvm/gems/ruby-2.6.5/bundler/gems/thredded-3f60a57c8c16/config/routes.rb:43:in `block (4 levels) in <main>'
        12: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:712:in `get'
        11: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:751:in `map_method'
        10: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1633:in `match'
         9: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1886:in `map_match'
         8: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1886:in `each'
         7: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1892:in `block in map_match'
         6: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1928:in `decomposed_match'
         5: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1956:in `add_route'
         4: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:83:in `build'
         3: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:83:in `new'
         2: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:131:in `initialize'
         1: from /home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:260:in `normalize_options!'
/home/denis/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:353:in `add_controller_module': undefined method `start_with?' for :moderation:Symbol (NoMethodError)
```
The exception disappears when thredded is deinstalled.

**Comment by fosterfarrell9** [comment]
This seems related to [this](https://github.com/rails/rails/issues/37857) rails issue which should be fixed in Rails 6.0.2.
