### ISSUE TITLE
Error when running view spec

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#865]
I get the following errors when trying to run spec/views/thredded/users/link_spec.rb

Not clear why it's not occurring on CI, but it seems related to the name. I have a fix in a PR.

  1) partial: thredded/users/link with null user
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: example.run
          
          NameError:
            wrong constant name Partial: thredded
          # /Users/tim/.rvm/gems/ruby-2.5.7@thredded/gems/activesupport-6.0.3.1/lib/active_support/inflector/methods.rb:282:in `const_get'
          # /Users/tim/.rvm/gems/ruby-2.5.7@thredded/gems/activesupport-6.0.3.1/lib/active_support/inflector/methods.rb:282:in `block in constantize'
          # /Users/tim/.rvm/gems/ruby-2.5.7@thredded/gems/activesupport-6.0.3.1/lib/active_support/inflector/methods.rb:280:in `each'
          # /Users/tim/.rvm/gems/ruby-2.5.7@thredded/gems/activesupport-6.0.3.1/lib/active_support/inflector/methods.rb:280:in `inject'
          # /Users/tim/.rvm/gems/ruby-2.5.7@thredded/gems/activesupport-6.0.3.1/lib/active_support/inflector/methods.rb:280:in `constantize'
          # /Users/tim/.rvm/gems/ruby-2.5.7@thredded/gems/activesupport-6.0.3.1/lib/active_support/dependencies/zeitwerk_integration.rb:19:in `constantize'
          # /Users/tim/.rvm/gems/ruby-2.5.7@thredded/gems/actionpack-6.0.3.1/lib/action_dispatch/http/request.rb:89:in `controller_class_for'
          # /Users/tim/.rvm/gems/ruby-2.5.7@thredded/gems/actionpack-6.0.3.1/lib/action_dispatch/http/parameters.rb:100:in `binary_params_for?'
          # /Users/tim/.rvm/gems/ruby-2.5.7@thredded/gems/actionpack-6.0.3.1/lib/action_dispatch/http/parameters.rb:91:in `set_binary_encoding'
          # /Users/tim/.rvm/gems/ruby-2.5.7@thredded/gems/actionpack-6.0.3.1/lib/action_dispatch/http/parameters.rb:69:in `path_parameters='
          # ./spec/support/thredded_reset.rb:6:in `block (2 levels) in <top (required)>'

     1.2) Failure/Error: example.run
          
          NoMethodError:
            undefined method `each' for nil:NilClass
          # /Users/tim/.rvm/gems/ruby-2.5.7@thredded/gems/rails-controller-testing-1.0.4/lib/rails/controller/testing/template_assertions.rb:54:in `teardown_subscriptions'
          # ./spec/support/thredded_reset.rb:6:in `block (2 levels) in <top (required)>'

**Comment by timdiggins** [comment]
Actually it is occurring on travis: https://travis-ci.org/github/thredded/thredded/jobs/692051300
