### ISSUE TITLE
Unable to resolve "thredded_imports.js" - Rails 6 Webpack

### ISSUE THREAD

**Issue by quakes27** [thredded/thredded#869]
I have a Rails 6 app using Webpack on Windows. Everything compiles and works normally in development environment but I get an error when pushing to production or run "yarn run webpack"
```
ERROR in ./app/javascript/packs/application.js
Module not found: Error: Can't resolve 'thredded_imports.js' in 'path\app\javascript\packs'
 @ ./app/javascript/packs/application.js 26:0-33
```
I have tried reinstalling webpack, erb loader, adding -.js.erb to my webpacker.yml. Adding loaders in my webpack.config.js, resolving extensions and none have worked. I have been searching and trying things for the past week but still nothing works.

I have also tried using relative paths (i.e. ../thredded_imports.js) without success.

I have also tried require("thredded_imports.js.erb") but that produces the following error:
```
ERROR in ./app/javascript/thredded_imports.js.erb
Module build failed (from ./node_modules/rails-erb-loader/index.js):
Error: spawn ./bin/rails ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 @ ./app/javascript/packs/application.js 27:0-37
```
Does anyone have an idea what it could be?
application.js
```
import 'core-js/stable'
import 'regenerator-runtime/runtime'

import ahoy from "ahoy.js"
import jQuery from "jquery"
import LocalTime from "local-time"
LocalTime.start()

require("trix")  // rich text editor
require("@rails/actiontext")
// require("turbolinks").start()
// require("@rails/ujs").start()

require("../conversations")
require("thredded_imports.js")
require("chartkick")
require("chart.js")

import NavToggler from '../components/NavToggler'
import Sidebar from '../components/Sidebar'
import Collapse from '../components/Collapse'
import ImageUploader from '../components/ImageUploader'

NavToggler('.navbar-toggler')
Sidebar('.sidebar')
Collapse('[data-toggle="collapse"]')

$(document).ready(function(){
	$('#main-content').on('click', '.toggle', function (e) {
	// $(".toggle").on('click', function (e) {
		e.preventDefault();
	  $(this).next().toggle('slow');
	});
})
```
webpack.config.js
```
const path = require('path');

module.exports = {
		mode: 'none',
		entry: {
			application: './app/javascript/packs/application.js',
		},
		module: {
			rules: [
				{
					test: /\.erb$/,
					enforce: 'pre',
					loader: 'rails-erb-loader'
				}
				]
		},
    output: {
      path: path.resolve(__dirname, './dist/'), 
      filename: "[name].bundle.js"
    },
}
```
environment.js
```
const { environment } = require('@rails/webpacker')
const erb = require('./loaders/erb')

environment.loaders.prepend('erb', erb)
module.exports = environment
```
package.json
```
{
  "private": true,
  "version": "1.0.0",
  "main": "application.js",
  "engines": {
    "node": "^12.16.2",
    "yarn": "^1.22.4"
  },
  "scripts": {
    "webpack": "webpack --watch --progress --display-error-details",
    "start": "webpack-dev-server --open",
    "dev": "webpack --mode=development",
    "build": "webpack --mode=production --env.production"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/preset-env": "^7.9.0",
    "autoprefixer": "^9.7.5",
    "babel-loader": "^8.1.0",
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^3.4.2",
    "file-loader": "^6.0.0",
    "html-webpack-plugin": "^4.0.4",
    "mini-css-extract-plugin": "^0.9.0",
    "node-sass": "^4.13.1",
    "postcss-font-magician": "^2.3.1",
    "postcss-loader": "^3.0.0",
    "sass-loader": "^8.0.2",
    "style-loader": "^1.1.3",
    "url-loader": "^4.0.0",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.11.0"
  },
  "dependencies": {
    "@fortawesome/fontawesome-free": "^5.11.2",
    "@popperjs/core": "^2.3.3",
    "@rails/actioncable": "^6.0.0",
    "@rails/actiontext": "6.0.2-1",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "5.1.1",
    "ahoy.js": "^0.3.5",
    "bootstrap": "^4.4.1",
    "chart.js": "^2.9.3",
    "chartkick": "^3.2.0",
    "enhanced-resolve": "^4.1.1",
    "jquery": "^3.5.1",
    "local-time": "^2.1.0",
    "popper.js": "^1.14.1",
    "quill": "^1.3.6",
    "rails-erb-loader": "^5.5.2",
    "trix": "1.0.0",
    "turbolinks": "^5.2.0"
  }
}
```

**Comment by quoyi** [comment]
[Note that you must use require](https://github.com/thredded/thredded/blob/master/README.md#add-thredded-javascripts-webpack) like this: `require('./thredded_imports.js');` **Relative path**
