### ISSUE TITLE
NoMethodError in Thredded::Topics#index in new installation 

### ISSUE THREAD

**Issue by donrestarone** [thredded/thredded#882]
Hey! This is a fantastic gem, but when I tried installing it in a new app I ran into an issue when trying to view a topic. 
It looks like the problem might be coming from action view. 

Im using: Rails 6.1.3 and Ruby 2.6.6 in a multitenant app (not sure if that matters, its using postgres and using separate schemas for tenants). 

``` bash
Completed 500 Internal Server Error in 37ms (ActiveRecord: 7.7ms | Allocations: 24536)
solutions_app        |
solutions_app        |
solutions_app        |
solutions_app        | ActionView::Template::Error (undefined method `size' for #<Thredded::TopicsPageView:0x0000555c36d549d0>):
solutions_app        |     13:                topic: @new_topic,
solutions_app        |     14:                css_class: 'thredded--is-compact',
solutions_app        |     15:                placeholder: t('thredded.topics.form.title_placeholder_start') if @new_topic %>
solutions_app        |     16:     <%= render partial: 'thredded/topics/topic',
solutions_app        |     17:                collection: @topics,
solutions_app        |     18:                locals: {
solutions_app        |     19:                    sticky_topics_divider: true,
solutions_app        |
solutions_app        | actionview (6.1.3.1) lib/action_view/renderer/collection_renderer.rb:48:in `size'
solutions_app        | actionview (6.1.3.1) lib/action_view/renderer/collection_renderer.rb:52:in `length'
solutions_app        | actionview (6.1.3.1) lib/action_view/renderer/collection_renderer.rb:151:in `render_collection'
solutions_app        | actionview (6.1.3.1) lib/action_view/renderer/collection_renderer.rb:119:in `render_collection_with_partial'
solutions_app        | actionview (6.1.3.1) lib/action_view/renderer/renderer.rb:72:in `render_partial_to_object'
solutions_app        | actionview (6.1.3.1) lib/action_view/renderer/renderer.rb:27:in `render_to_object'
solutions_app        | actionview (6.1.3.1) lib/action_view/renderer/renderer.rb:22:in `render'
solutions_app        | actionview (6.1.3.1) lib/action_view/helpers/rendering_helper.rb:38:in `block in render'
solutions_app        | actionview (6.1.3.1) lib/action_view/base.rb:273:in `in_rendering_context'
solutions_app        | actionview (6.1.3.1) lib/action_view/helpers/rendering_helper.rb:34:in `render'
solutions_app        | haml (5.2.1) lib/haml/helpers/action_view_mods.rb:15:in `render'
solutions_app        | thredded (0.16.16) app/views/thredded/topics/index.html.erb:16
solutions_app        | actionview (6.1.3.1) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
solutions_app        | actionview (6.1.3.1) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
solutions_app        | haml (5.2.1) lib/haml/helpers/action_view_xss_mods.rb:7:in `with_output_buffer_with_haml_xss'
solutions_app        | actionview (6.1.3.1) lib/action_view/helpers/capture_helper.rb:45:in `capture'
solutions_app        | haml (5.2.1) lib/haml/helpers/action_view_mods.rb:48:in `capture_with_haml'
solutions_app        | actionview (6.1.3.1) lib/action_view/helpers/tag_helper.rb:310:in `content_tag'
solutions_app        | haml (5.2.1) lib/haml/helpers/action_view_mods.rb:59:in `content_tag_with_haml'
solutions_app        | thredded (0.16.16) app/views/thredded/topics/index.html.erb:8
solutions_app        | actionview (6.1.3.1) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
solutions_app        | actionview (6.1.3.1) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
solutions_app        | haml (5.2.1) lib/haml/helpers/action_view_xss_mods.rb:7:in `with_output_buffer_with_haml_xss'
solutions_app        | actionview (6.1.3.1) lib/action_view/helpers/capture_helper.rb:45:in `capture'
solutions_app        | haml (5.2.1) lib/haml/helpers/action_view_mods.rb:48:in `capture_with_haml'
solutions_app        | actionview (6.1.3.1) lib/action_view/helpers/capture_helper.rb:159:in `content_for'
solutions_app        | thredded (0.16.16) app/helpers/thredded/application_helper.rb:44:in `thredded_page'
solutions_app        | thredded (0.16.16) app/views/thredded/topics/index.html.erb:5
solutions_app        | actionview (6.1.3.1) lib/action_view/base.rb:247:in `public_send'
solutions_app        | actionview (6.1.3.1) lib/action_view/base.rb:247:in `_run'
solutions_app        | actionview (6.1.3.1) lib/action_view/template.rb:154:in `block in render'
solutions_app        | activesupport (6.1.3.1) lib/active_support/notifications.rb:205:in `instrument'
solutions_app        | actionview (6.1.3.1) lib/action_view/template.rb:345:in `instrument_render_template'
solutions_app        | actionview (6.1.3.1) lib/action_view/template.rb:152:in `render'
solutions_app        | actionview (6.1.3.1) lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
solutions_app        | activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `block in instrument'
solutions_app        | activesupport (6.1.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
solutions_app        | activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `instrument'
solutions_app        | actionview (6.1.3.1) lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
solutions_app        | actionview (6.1.3.1) lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'
solutions_app        | activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `block in instrument'
solutions_app        | activesupport (6.1.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
solutions_app        | activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `instrument'
solutions_app        | actionview (6.1.3.1) lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
solutions_app        | actionview (6.1.3.1) lib/action_view/renderer/template_renderer.rb:55:in `render_template'
solutions_app        | actionview (6.1.3.1) lib/action_view/renderer/template_renderer.rb:11:in `render'
solutions_app        | actionview (6.1.3.1) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
solutions_app        | actionview (6.1.3.1) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
solutions_app        | actionview (6.1.3.1) lib/action_view/rendering.rb:117:in `block in _render_template'
solutions_app        | actionview (6.1.3.1) lib/action_view/base.rb:273:in `in_rendering_context'
solutions_app        | actionview (6.1.3.1) lib/action_view/rendering.rb:116:in `_render_template'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/streaming.rb:218:in `_render_template'
solutions_app        | actionview (6.1.3.1) lib/action_view/rendering.rb:103:in `render_to_body'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
solutions_app        | actionpack (6.1.3.1) lib/abstract_controller/rendering.rb:25:in `render'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/rendering.rb:36:in `render'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
solutions_app        | /usr/local/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
solutions_app        | activesupport (6.1.3.1) lib/active_support/core_ext/benchmark.rb:14:in `ms'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
solutions_app        | activerecord (6.1.3.1) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:45:in `render'
solutions_app        | comfortable-mexican-sofa (fd230aee88a0) lib/comfortable_mexican_sofa/render_methods.rb:59:in `render'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
solutions_app        | actionpack (6.1.3.1) lib/abstract_controller/base.rb:228:in `process_action'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
solutions_app        | actionpack (6.1.3.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
solutions_app        | activesupport (6.1.3.1) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
solutions_app        | actiontext (6.1.3.1) lib/action_text/rendering.rb:20:in `with_renderer'
solutions_app        | actiontext (6.1.3.1) lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
solutions_app        | activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `instance_exec'
solutions_app        | activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
solutions_app        | activesupport (6.1.3.1) lib/active_support/callbacks.rb:137:in `run_callbacks'
solutions_app        | actionpack (6.1.3.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
solutions_app        | activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `block in instrument'
solutions_app        | activesupport (6.1.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
solutions_app        | activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `instrument'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
solutions_app        | activerecord (6.1.3.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
solutions_app        | actionpack (6.1.3.1) lib/abstract_controller/base.rb:165:in `process'
solutions_app        | actionview (6.1.3.1) lib/action_view/rendering.rb:39:in `process'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal.rb:190:in `dispatch'
solutions_app        | actionpack (6.1.3.1) lib/action_controller/metal.rb:254:in `dispatch'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `each'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
solutions_app        | railties (6.1.3.1) lib/rails/engine.rb:539:in `call'
solutions_app        | railties (6.1.3.1) lib/rails/railtie.rb:207:in `public_send'
solutions_app        | railties (6.1.3.1) lib/rails/railtie.rb:207:in `method_missing'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `each'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
solutions_app        | ros-apartment (2.9.0) lib/apartment/elevators/generic.rb:22:in `block in call'
solutions_app        | ros-apartment (2.9.0) lib/apartment/adapters/abstract_adapter.rb:89:in `switch'
solutions_app        | /usr/local/lib/ruby/2.6.0/forwardable.rb:230:in `switch'
solutions_app        | ros-apartment (2.9.0) lib/apartment/elevators/generic.rb:22:in `call'
solutions_app        | ros-apartment (2.9.0) lib/apartment/reloader.rb:19:in `call'
solutions_app        | warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
solutions_app        | warden (1.2.9) lib/warden/manager.rb:34:in `catch'
solutions_app        | warden (1.2.9) lib/warden/manager.rb:34:in `call'
solutions_app        | rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
solutions_app        | rack (2.2.3) lib/rack/etag.rb:27:in `call'
solutions_app        | rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
solutions_app        | rack (2.2.3) lib/rack/head.rb:12:in `call'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
solutions_app        | rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
solutions_app        | rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'
solutions_app        | activerecord (6.1.3.1) lib/active_record/migration.rb:601:in `call'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
solutions_app        | activesupport (6.1.3.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
solutions_app        | web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
solutions_app        | web-console (4.1.0) lib/web_console/middleware.rb:19:in `block in call'
solutions_app        | web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
solutions_app        | web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
solutions_app        | railties (6.1.3.1) lib/rails/rack/logger.rb:37:in `call_app'
solutions_app        | railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `block in call'
solutions_app        | activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
solutions_app        | activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:37:in `tagged'
solutions_app        | activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `tagged'
solutions_app        | railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `call'
solutions_app        | sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
solutions_app        | rack (2.2.3) lib/rack/method_override.rb:24:in `call'
solutions_app        | rack (2.2.3) lib/rack/runtime.rb:22:in `call'
solutions_app        | activesupport (6.1.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/middleware/static.rb:24:in `call'
solutions_app        | rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
solutions_app        | actionpack (6.1.3.1) lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
solutions_app        | rack-mini-profiler (2.3.1) lib/mini_profiler/profiler.rb:373:in `call'
solutions_app        | webpacker (5.2.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
solutions_app        | rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
solutions_app        | railties (6.1.3.1) lib/rails/engine.rb:539:in `call'
solutions_app        | puma (5.2.2) lib/puma/configuration.rb:248:in `call'
solutions_app        | puma (5.2.2) lib/puma/request.rb:76:in `block in handle_request'
solutions_app        | puma (5.2.2) lib/puma/thread_pool.rb:337:in `with_force_shutdown'
solutions_app        | puma (5.2.2) lib/puma/request.rb:75:in `handle_request'
solutions_app        | puma (5.2.2) lib/puma/server.rb:431:in `process_client'
solutions_app        | puma (5.2.2) lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

Any guidance on this would be greatly appreciated! I have started debugging this issue on my own branch but so far haven't been able to. I'm open to debugging tips as well, thanks in advance!

**Comment by glebm** [comment]
Rails 6.1 is not yet supported
