### ISSUE TITLE
CI broken on master

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#895]
I got travis-ci.com building, but it's broken on master. 

my plan to fix this would be:

* [x] drop the rails 4.2 -> 5.1 elements of the matrix (to make it faster) in prep for #885 
* [x]  upgrade the ruby version on the matrix to a non-EOLed version
* [ ] investigate any other needed fixes

**Comment by timdiggins** [comment]
The manifest problem appears to be because of using execjs > 2.7 (see https://github.com/rails/execjs/issues/99), e.g. 

https://travis-ci.com/github/thredded/thredded/jobs/524171102#L1502

```
  1) User sends a new private topic with title, recipient and content
     Failure/Error: <%= stylesheet_link_tag current_theme, media: 'all', 'data-turbolinks-track' => 'reload' %>
     
     ActionView::Template::Error:
       TypeError: Cannot read property 'version' of undefined
     # eval (eval at __process__ ((execjs):1:275), <anonymous>:1:10)
     # __process__ ((execjs):1:275)
     # (execjs):19:14
     # (execjs):1:102
     # Object.<anonymous> ((execjs):1:120)
     # Module._compile (module.js:653:30)
     # Object.Module._extensions..js (module.js:664:10)
     # Module.load (module.js:566:32)
     # tryModuleLoad (module.js:506:12)
     # Function.Module._load (module.js:498:3)
     # ./spec/dummy/app/views/layouts/application.html.erb:7:in `_app_views_layouts_application_html_erb___1348966612662977091_88828580'
     # ./spec/support/features/page_object/user.rb:17:in `log_in'
     # ./spec/features/thredded/user_sends_new_private_topic_spec.rb:7:in `block (2 levels) in <top (required)>'
     # ./spec/support/thredded_reset.rb:6:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ExecJS::ProgramError:
     #   TypeError: Cannot read property 'version' of undefined
     #   eval (eval at __process__ ((execjs):1:275), <anonymous>:1:10)
```

However I can't reproduce on my machine using an up to date ruby, so trying with up to date rubies first.
