### ISSUE TITLE
 Cannot load such file -- html/pipeline (LoadError)

### ISSUE THREAD

**Issue by kvoshell** [thredded/thredded#979]
Attempting to add `thredded` to an existing app (Rails 7.0.0, ruby 3.2.0) throws a LoadError

```
➜  rails generate thredded:install
/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require': cannot load such file -- html/pipeline (LoadError)
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/thredded-1.1.0/lib/thredded.rb:8:in `<main>'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/runtime.rb:55:in `each'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/runtime.rb:55:in `block in require'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/runtime.rb:44:in `each'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler/runtime.rb:44:in `require'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.5/lib/bundler.rb:195:in `require'
	from /projects/config/application.rb:7:in `<main>'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4.2/lib/rails/command/actions.rb:22:in `require_application!'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4.2/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4.2/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4.2/lib/rails/command/base.rb:87:in `perform'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4.2/lib/rails/command.rb:48:in `invoke'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4.2/lib/rails/commands.rb:18:in `<main>'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by kvoshell** [comment]
Adding `gem "html-pipeline", "~> 2.14"` will allow the initializer to load, so I'm assuming there's been an incompatibility introduced in v3+ of `html-pipeline`

**Comment by timdiggins** [comment]
@kvoshell thanks for the report and workaround.

**Comment by rickychilcott** [comment]
With the pinned `html-pipeline` dependency #981. I think this can be closed.
